using System.Globalization;
using System.Text;
using Google.Protobuf.WellKnownTypes;
using QsoRipper.Domain;

namespace QsoRipper.Engine.DotNet;

internal static class ManagedAdifCodec
{
    public const int ChunkSize = 16 * 1024;

    private const string AdifVersion = "3.1.7";
    private const string ProgramId = "QsoRipper";
    private const string SubmodeAliasesResourceName = "QsoRipper.Engine.DotNet.submode_aliases.tsv";
    private const string DxccEntitiesResourceName = "QsoRipper.Engine.DotNet.dxcc_entities.tsv";

    private static readonly (string Name, Band Band)[] BandTable =
    [
        ("2190M", Band._2190M),
        ("630M", Band._630M),
        ("560M", Band._560M),
        ("160M", Band._160M),
        ("80M", Band._80M),
        ("60M", Band._60M),
        ("40M", Band._40M),
        ("30M", Band._30M),
        ("20M", Band._20M),
        ("17M", Band._17M),
        ("15M", Band._15M),
        ("12M", Band._12M),
        ("10M", Band._10M),
        ("8M", Band._8M),
        ("6M", Band._6M),
        ("5M", Band._5M),
        ("4M", Band._4M),
        ("2M", Band._2M),
        ("1.25M", Band._125M),
        ("70CM", Band._70Cm),
        ("33CM", Band._33Cm),
        ("23CM", Band._23Cm),
        ("13CM", Band._13Cm),
        ("9CM", Band._9Cm),
        ("6CM", Band._6Cm),
        ("3CM", Band._3Cm),
        ("1.25CM", Band._125Cm),
        ("6MM", Band._6Mm),
        ("4MM", Band._4Mm),
        ("2.5MM", Band._25Mm),
        ("2MM", Band._2Mm),
        ("1MM", Band._1Mm),
        ("SUBMM", Band.Submm),
    ];

    private static readonly (string Name, Mode Mode)[] ModeTable =
    [
        ("AM", Mode.Am),
        ("ARDOP", Mode.Ardop),
        ("ATV", Mode.Atv),
        ("CHIP", Mode.Chip),
        ("CLO", Mode.Clo),
        ("CONTESTI", Mode.Contesti),
        ("CW", Mode.Cw),
        ("DIGITALVOICE", Mode.Digitalvoice),
        ("DOMINO", Mode.Domino),
        ("DYNAMIC", Mode.Dynamic),
        ("FAX", Mode.Fax),
        ("FM", Mode.Fm),
        ("FSK", Mode.Fsk),
        ("FT8", Mode.Ft8),
        ("HELL", Mode.Hell),
        ("ISCAT", Mode.Iscat),
        ("JT4", Mode.Jt4),
        ("JT9", Mode.Jt9),
        ("JT44", Mode.Jt44),
        ("JT65", Mode.Jt65),
        ("MFSK", Mode.Mfsk),
        ("MTONE", Mode.Mtone),
        ("MSK144", Mode.Msk144),
        ("OFDM", Mode.Ofdm),
        ("OLIVIA", Mode.Olivia),
        ("OPERA", Mode.Opera),
        ("PAC", Mode.Pac),
        ("PAX", Mode.Pax),
        ("PKT", Mode.Pkt),
        ("PSK", Mode.Psk),
        ("Q15", Mode.Q15),
        ("QRA64", Mode.Qra64),
        ("ROS", Mode.Ros),
        ("RTTY", Mode.Rtty),
        ("RTTYM", Mode.Rttym),
        ("SSB", Mode.Ssb),
        ("SSTV", Mode.Sstv),
        ("T10", Mode.T10),
        ("THOR", Mode.Thor),
        ("THRB", Mode.Thrb),
        ("TOR", Mode.Tor),
        ("V4", Mode.V4),
        ("VOI", Mode.Voi),
        ("WINMOR", Mode.Winmor),
        ("WSPR", Mode.Wspr),
    ];

    private static readonly Dictionary<string, Band> AdifToBand = BandTable.ToDictionary(
        entry => entry.Name,
        entry => entry.Band,
        StringComparer.OrdinalIgnoreCase);

    private static readonly Dictionary<Band, string> BandToAdif = BandTable.ToDictionary(
        entry => entry.Band,
        entry => entry.Name);

    private static readonly Dictionary<string, Mode> AdifToMode = ModeTable.ToDictionary(
        entry => entry.Name,
        entry => entry.Mode,
        StringComparer.OrdinalIgnoreCase);

    private static readonly Dictionary<Mode, string> ModeToAdif = ModeTable.ToDictionary(
        entry => entry.Mode,
        entry => entry.Name);

    private static readonly Lazy<Dictionary<string, (string Submode, Mode Mode)>> SubmodeAliases = new(LoadSubmodeAliases);
    private static readonly Lazy<Dictionary<uint, DxccEntityInfo>> DxccEntities = new(LoadDxccEntities);

    public static IReadOnlyList<QsoRecord> ParseAdiQsos(byte[] data)
    {
        ArgumentNullException.ThrowIfNull(data);

        var text = Encoding.UTF8.GetString(data);
        return ParseRecords(text)
            .Select(RecordToQso)
            .ToArray();
    }

    public static byte[] SerializeAdiQsos(IEnumerable<QsoRecord> qsos, bool includeHeader)
    {
        ArgumentNullException.ThrowIfNull(qsos);

        var output = new StringBuilder();
        if (includeHeader)
        {
            output.Append("Generated by QsoRipper\n");
            AppendField(output, "ADIF_VER", AdifVersion);
            AppendField(output, "PROGRAMID", ProgramId);
            AppendField(output, "PROGRAMVERSION", typeof(ManagedEngineState).Assembly.GetName().Version?.ToString() ?? "0.0.0");
            output.Append("<EOH>\n");
        }

        foreach (var qso in qsos)
        {
            var fields = QsoToAdifFields(qso);
            foreach (var field in fields)
            {
                AppendField(output, field.Key, field.Value);
            }

            output.Append("<eor>\n");
        }

        return Encoding.UTF8.GetBytes(output.ToString());
    }

    private static List<Dictionary<string, string>> ParseRecords(string text)
    {
        var records = new List<Dictionary<string, string>>();
        var current = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        var inHeader = text.Contains("<EOH>", StringComparison.OrdinalIgnoreCase);
        var index = 0;

        while (index < text.Length)
        {
            var tagStart = text.IndexOf('<', index);
            if (tagStart < 0)
            {
                break;
            }

            var tagEnd = text.IndexOf('>', tagStart + 1);
            if (tagEnd < 0)
            {
                throw new InvalidOperationException("ADIF parse error: unterminated tag.");
            }

            var rawTag = text[(tagStart + 1)..tagEnd].Trim();
            index = tagEnd + 1;
            if (rawTag.Length == 0)
            {
                continue;
            }

            if (rawTag.Equals("EOH", StringComparison.OrdinalIgnoreCase))
            {
                inHeader = false;
                current.Clear();
                continue;
            }

            if (rawTag.Equals("EOR", StringComparison.OrdinalIgnoreCase))
            {
                if (!inHeader && current.Count > 0)
                {
                    records.Add(current);
                    current = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                }

                continue;
            }

            var colonIndex = rawTag.AsSpan().IndexOf(':');
            if (colonIndex < 0)
            {
                throw new InvalidOperationException($"ADIF parse error: tag '{rawTag}' is missing a length.");
            }

            var key = rawTag[..colonIndex].Trim();
            if (key.Length == 0)
            {
                throw new InvalidOperationException("ADIF parse error: field name is empty.");
            }

            var lengthPart = rawTag[(colonIndex + 1)..];
            var typeSeparator = lengthPart.AsSpan().IndexOf(':');
            if (typeSeparator >= 0)
            {
                lengthPart = lengthPart[..typeSeparator];
            }

            if (!int.TryParse(lengthPart, NumberStyles.None, CultureInfo.InvariantCulture, out var valueLength) || valueLength < 0)
            {
                throw new InvalidOperationException($"ADIF parse error: invalid length '{lengthPart}' for field '{key}'.");
            }

            if (index + valueLength > text.Length)
            {
                throw new InvalidOperationException($"ADIF parse error: field '{key}' overruns the input payload.");
            }

            var value = text.Substring(index, valueLength);
            index += valueLength;

            if (!inHeader)
            {
                current[key.ToUpperInvariant()] = value;
            }
        }

        if (!inHeader && current.Count > 0)
        {
            records.Add(current);
        }

        return records;
    }

    private static QsoRecord RecordToQso(IReadOnlyDictionary<string, string> record)
    {
        var qso = new QsoRecord
        {
            LocalId = Guid.NewGuid().ToString(),
            SyncStatus = SyncStatus.LocalOnly,
        };
        StationSnapshot? stationSnapshot = null;
        string? qsoDate = null;
        string? timeOn = null;
        string? qsoDateOff = null;
        string? timeOff = null;

        foreach (var pair in record)
        {
            var key = pair.Key.ToUpperInvariant();
            var value = pair.Value;

            switch (key)
            {
                case "CALL":
                    qso.WorkedCallsign = value;
                    break;
                case "STATION_CALLSIGN":
                    qso.StationCallsign = value;
                    (stationSnapshot ??= new StationSnapshot()).StationCallsign = value;
                    break;
                case "OPERATOR":
                    (stationSnapshot ??= new StationSnapshot()).OperatorCallsign = value;
                    if (string.IsNullOrWhiteSpace(qso.StationCallsign))
                    {
                        qso.StationCallsign = value;
                        (stationSnapshot ??= new StationSnapshot()).StationCallsign = value;
                    }

                    break;
                case "QSO_DATE":
                    qsoDate = value;
                    break;
                case "TIME_ON":
                    timeOn = value;
                    break;
                case "QSO_DATE_OFF":
                    qsoDateOff = value;
                    break;
                case "TIME_OFF":
                    timeOff = value;
                    break;
                case "BAND":
                    if (AdifToBand.TryGetValue(value, out var band))
                    {
                        qso.Band = band;
                    }
                    else
                    {
                        qso.ExtraFields[key] = value;
                    }

                    break;
                case "MODE":
                    if (TryNormalizeModeFromAdif(value, out var mode, out var submode))
                    {
                        qso.Mode = mode;
                        if (submode is not null && !qso.HasSubmode)
                        {
                            qso.Submode = submode;
                        }
                    }
                    else
                    {
                        qso.ExtraFields[key] = value;
                    }

                    break;
                case "SUBMODE":
                    qso.Submode = value;
                    break;
                case "FREQ":
                    if (double.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out var mhz)
                        && TryConvertMhzToKhz(mhz, out var khz))
                    {
                        qso.FrequencyKhz = khz;
                    }
                    else
                    {
                        qso.ExtraFields[key] = value;
                    }

                    break;
                case "RST_SENT":
                    qso.RstSent = ParseRstReport(value);
                    break;
                case "RST_RCVD":
                    qso.RstReceived = ParseRstReport(value);
                    break;
                case "TX_PWR":
                    qso.TxPower = value;
                    break;
                case "CONTACTED_OP":
                    qso.WorkedOperatorCallsign = value;
                    break;
                case "NAME":
                    qso.WorkedOperatorName = value;
                    break;
                case "GRIDSQUARE":
                    qso.WorkedGrid = value;
                    break;
                case "COUNTRY":
                    qso.WorkedCountry = value;
                    break;
                case "DXCC":
                    if (uint.TryParse(value, NumberStyles.None, CultureInfo.InvariantCulture, out var dxcc))
                    {
                        qso.WorkedDxcc = dxcc;
                    }

                    break;
                case "STATE":
                    qso.WorkedState = value;
                    break;
                case "CNTY":
                    qso.WorkedCounty = value;
                    break;
                case "CONT":
                    qso.WorkedContinent = value;
                    break;
                case "CQZ":
                    if (uint.TryParse(value, NumberStyles.None, CultureInfo.InvariantCulture, out var cqZone))
                    {
                        qso.WorkedCqZone = cqZone;
                    }

                    break;
                case "ITUZ":
                    if (uint.TryParse(value, NumberStyles.None, CultureInfo.InvariantCulture, out var ituZone))
                    {
                        qso.WorkedItuZone = ituZone;
                    }

                    break;
                case "IOTA":
                    qso.WorkedIota = value;
                    break;
                case "ARRL_SECT":
                    qso.WorkedArrlSection = value;
                    break;
                case "SKCC":
                    qso.Skcc = value;
                    break;
                case "MY_NAME":
                    (stationSnapshot ??= new StationSnapshot()).OperatorName = value;
                    break;
                case "MY_GRIDSQUARE":
                    (stationSnapshot ??= new StationSnapshot()).Grid = value;
                    break;
                case "MY_CNTY":
                    (stationSnapshot ??= new StationSnapshot()).County = value;
                    break;
                case "MY_STATE":
                    (stationSnapshot ??= new StationSnapshot()).State = value;
                    break;
                case "MY_COUNTRY":
                    (stationSnapshot ??= new StationSnapshot()).Country = value;
                    break;
                case "MY_DXCC":
                    if (uint.TryParse(value, NumberStyles.None, CultureInfo.InvariantCulture, out var myDxcc))
                    {
                        (stationSnapshot ??= new StationSnapshot()).Dxcc = myDxcc;
                    }
                    else
                    {
                        qso.ExtraFields[key] = value;
                    }

                    break;
                case "MY_CQ_ZONE":
                    if (uint.TryParse(value, NumberStyles.None, CultureInfo.InvariantCulture, out var myCqZone))
                    {
                        (stationSnapshot ??= new StationSnapshot()).CqZone = myCqZone;
                    }
                    else
                    {
                        qso.ExtraFields[key] = value;
                    }

                    break;
                case "MY_ITU_ZONE":
                    if (uint.TryParse(value, NumberStyles.None, CultureInfo.InvariantCulture, out var myItuZone))
                    {
                        (stationSnapshot ??= new StationSnapshot()).ItuZone = myItuZone;
                    }
                    else
                    {
                        qso.ExtraFields[key] = value;
                    }

                    break;
                case "MY_LAT":
                    if (TryParseAdifLocation(value, latitude: true, out var latitude))
                    {
                        (stationSnapshot ??= new StationSnapshot()).Latitude = latitude;
                    }
                    else
                    {
                        qso.ExtraFields[key] = value;
                    }

                    break;
                case "MY_LON":
                    if (TryParseAdifLocation(value, latitude: false, out var longitude))
                    {
                        (stationSnapshot ??= new StationSnapshot()).Longitude = longitude;
                    }
                    else
                    {
                        qso.ExtraFields[key] = value;
                    }

                    break;
                case "MY_ARRL_SECT":
                    (stationSnapshot ??= new StationSnapshot()).ArrlSection = value;
                    break;
                case "QSL_SENT":
                    qso.QslSentStatus = ParseQslStatus(value);
                    break;
                case "QSL_RCVD":
                    qso.QslReceivedStatus = ParseQslStatus(value);
                    break;
                case "QSLSDATE":
                    if (TryParseAdifDateTime(value, null, out var qslSentDate))
                    {
                        qso.QslSentDate = qslSentDate;
                    }
                    else
                    {
                        qso.ExtraFields[key] = value;
                    }

                    break;
                case "QSLRDATE":
                    if (TryParseAdifDateTime(value, null, out var qslReceivedDate))
                    {
                        qso.QslReceivedDate = qslReceivedDate;
                    }
                    else
                    {
                        qso.ExtraFields[key] = value;
                    }

                    break;
                case "LOTW_QSL_SENT":
                    MapConfirmationField(qso, key, value, (recordValue, parsed) => recordValue.LotwSent = parsed);
                    break;
                case "LOTW_QSL_RCVD":
                    MapConfirmationField(qso, key, value, (recordValue, parsed) => recordValue.LotwReceived = parsed);
                    break;
                case "EQSL_QSL_SENT":
                    MapConfirmationField(qso, key, value, (recordValue, parsed) => recordValue.EqslSent = parsed);
                    break;
                case "EQSL_QSL_RCVD":
                    MapConfirmationField(qso, key, value, (recordValue, parsed) => recordValue.EqslReceived = parsed);
                    break;
                case "CONTEST_ID":
                    qso.ContestId = value;
                    break;
                case "SRX":
                    qso.SerialReceived = value;
                    break;
                case "STX":
                    qso.SerialSent = value;
                    break;
                case "SRX_STRING":
                    qso.ExchangeReceived = value;
                    break;
                case "STX_STRING":
                    qso.ExchangeSent = value;
                    break;
                case "PROP_MODE":
                    qso.PropMode = value;
                    break;
                case "SAT_NAME":
                    qso.SatName = value;
                    break;
                case "SAT_MODE":
                    qso.SatMode = value;
                    break;
                case "COMMENT":
                    qso.Comment = value;
                    break;
                case "NOTES":
                    qso.Notes = value;
                    break;
                default:
                    qso.ExtraFields[key] = value;
                    break;
            }
        }

        if (qsoDate is not null)
        {
            if (TryParseAdifDateTime(qsoDate, timeOn, out var timestamp))
            {
                qso.UtcTimestamp = timestamp;
            }
            else
            {
                qso.ExtraFields["QSO_DATE"] = qsoDate;
                if (timeOn is not null)
                {
                    qso.ExtraFields["TIME_ON"] = timeOn;
                }
            }
        }
        else if (timeOn is not null)
        {
            qso.ExtraFields["TIME_ON"] = timeOn;
        }

        if (timeOff is not null)
        {
            var endDate = qsoDateOff ?? qsoDate;
            if (endDate is not null)
            {
                if (TryParseAdifDateTime(endDate, timeOff, out var endTimestamp))
                {
                    qso.UtcEndTimestamp = endTimestamp;
                }
                else
                {
                    if (qsoDateOff is not null)
                    {
                        qso.ExtraFields["QSO_DATE_OFF"] = qsoDateOff;
                    }

                    qso.ExtraFields["TIME_OFF"] = timeOff;
                }
            }
            else
            {
                qso.ExtraFields["TIME_OFF"] = timeOff;
            }
        }
        else if (qsoDateOff is not null)
        {
            qso.ExtraFields["QSO_DATE_OFF"] = qsoDateOff;
        }

        EnrichFromDxcc(qso);
        if (stationSnapshot is not null && ManagedQsoParity.StationSnapshotHasValues(stationSnapshot))
        {
            qso.StationSnapshot = stationSnapshot;
        }

        return qso;
    }

    private static List<KeyValuePair<string, string>> QsoToAdifFields(QsoRecord qso)
    {
        var fields = new List<KeyValuePair<string, string>>(qso.ExtraFields.Count + 32);
        var stationSnapshot = ManagedQsoParity.EffectiveStationSnapshot(qso);

        var stationCallsign = stationSnapshot is not null && !string.IsNullOrEmpty(stationSnapshot.StationCallsign)
            ? stationSnapshot.StationCallsign
            : (!string.IsNullOrEmpty(qso.StationCallsign) ? qso.StationCallsign : null);
        if (!string.IsNullOrEmpty(stationCallsign))
        {
            fields.Add(new KeyValuePair<string, string>("STATION_CALLSIGN", stationCallsign));
        }

        if (!string.IsNullOrEmpty(qso.WorkedCallsign))
        {
            fields.Add(new KeyValuePair<string, string>("CALL", qso.WorkedCallsign));
        }

        if (stationSnapshot is not null && !string.IsNullOrEmpty(stationSnapshot.OperatorCallsign))
        {
            fields.Add(new KeyValuePair<string, string>("OPERATOR", stationSnapshot.OperatorCallsign));
        }

        if (qso.UtcTimestamp is not null && TryFormatAdifDateTime(qso.UtcTimestamp, out var date, out var time))
        {
            fields.Add(new KeyValuePair<string, string>("QSO_DATE", date));
            fields.Add(new KeyValuePair<string, string>("TIME_ON", time));
        }

        if (qso.UtcEndTimestamp is not null && TryFormatAdifDateTime(qso.UtcEndTimestamp, out var endDate, out var endTime))
        {
            fields.Add(new KeyValuePair<string, string>("QSO_DATE_OFF", endDate));
            fields.Add(new KeyValuePair<string, string>("TIME_OFF", endTime));
        }

        if (BandToAdif.TryGetValue(qso.Band, out var band))
        {
            fields.Add(new KeyValuePair<string, string>("BAND", band));
        }

        if (ModeToAdif.TryGetValue(qso.Mode, out var mode))
        {
            fields.Add(new KeyValuePair<string, string>("MODE", mode));
        }

        if (qso.HasSubmode && !string.IsNullOrWhiteSpace(qso.Submode))
        {
            fields.Add(new KeyValuePair<string, string>("SUBMODE", qso.Submode));
        }

        if (qso.HasFrequencyKhz)
        {
            fields.Add(new KeyValuePair<string, string>("FREQ", $"{qso.FrequencyKhz / 1000}.{qso.FrequencyKhz % 1000:000}"));
        }

        if (qso.RstSent is not null)
        {
            fields.Add(new KeyValuePair<string, string>("RST_SENT", qso.RstSent.Raw));
        }

        if (qso.RstReceived is not null)
        {
            fields.Add(new KeyValuePair<string, string>("RST_RCVD", qso.RstReceived.Raw));
        }

        if (!string.IsNullOrWhiteSpace(qso.TxPower))
        {
            fields.Add(new KeyValuePair<string, string>("TX_PWR", qso.TxPower));
        }

        AddOptionalStringField(fields, "CONTACTED_OP", qso.WorkedOperatorCallsign);
        AddOptionalStringField(fields, "NAME", qso.WorkedOperatorName);
        AddOptionalStringField(fields, "GRIDSQUARE", qso.WorkedGrid);
        AddOptionalStringField(fields, "COUNTRY", qso.WorkedCountry);
        if (qso.HasWorkedDxcc)
        {
            fields.Add(new KeyValuePair<string, string>("DXCC", qso.WorkedDxcc.ToString(CultureInfo.InvariantCulture)));
        }

        AddOptionalStringField(fields, "STATE", qso.WorkedState);
        AddOptionalStringField(fields, "CNTY", qso.WorkedCounty);
        AddOptionalStringField(fields, "CONT", qso.WorkedContinent);
        if (qso.HasWorkedCqZone)
        {
            fields.Add(new KeyValuePair<string, string>("CQZ", qso.WorkedCqZone.ToString(CultureInfo.InvariantCulture)));
        }

        if (qso.HasWorkedItuZone)
        {
            fields.Add(new KeyValuePair<string, string>("ITUZ", qso.WorkedItuZone.ToString(CultureInfo.InvariantCulture)));
        }

        AddOptionalStringField(fields, "IOTA", qso.WorkedIota);
        AddOptionalStringField(fields, "ARRL_SECT", qso.WorkedArrlSection);
        AddOptionalStringField(fields, "SKCC", qso.Skcc);

        if (stationSnapshot is not null)
        {
            AddOptionalStringField(fields, "MY_NAME", stationSnapshot.OperatorName);
            AddOptionalStringField(fields, "MY_GRIDSQUARE", stationSnapshot.Grid);
            AddOptionalStringField(fields, "MY_CNTY", stationSnapshot.County);
            AddOptionalStringField(fields, "MY_STATE", stationSnapshot.State);
            AddOptionalStringField(fields, "MY_COUNTRY", stationSnapshot.Country);
            if (stationSnapshot.Dxcc > 0)
            {
                fields.Add(new KeyValuePair<string, string>("MY_DXCC", stationSnapshot.Dxcc.ToString(CultureInfo.InvariantCulture)));
            }

            if (stationSnapshot.CqZone > 0)
            {
                fields.Add(new KeyValuePair<string, string>("MY_CQ_ZONE", stationSnapshot.CqZone.ToString(CultureInfo.InvariantCulture)));
            }

            if (stationSnapshot.ItuZone > 0)
            {
                fields.Add(new KeyValuePair<string, string>("MY_ITU_ZONE", stationSnapshot.ItuZone.ToString(CultureInfo.InvariantCulture)));
            }

            if (stationSnapshot.Latitude != 0 && TryFormatAdifLocation(stationSnapshot.Latitude, latitude: true, out var myLatitude))
            {
                fields.Add(new KeyValuePair<string, string>("MY_LAT", myLatitude));
            }

            if (stationSnapshot.Longitude != 0 && TryFormatAdifLocation(stationSnapshot.Longitude, latitude: false, out var myLongitude))
            {
                fields.Add(new KeyValuePair<string, string>("MY_LON", myLongitude));
            }

            AddOptionalStringField(fields, "MY_ARRL_SECT", stationSnapshot.ArrlSection);
        }

        if (TryFormatQslStatus(qso.QslSentStatus, out var sentStatus))
        {
            fields.Add(new KeyValuePair<string, string>("QSL_SENT", sentStatus));
        }

        if (TryFormatQslStatus(qso.QslReceivedStatus, out var receivedStatus))
        {
            fields.Add(new KeyValuePair<string, string>("QSL_RCVD", receivedStatus));
        }

        if (qso.QslSentDate is not null && TryFormatAdifDate(qso.QslSentDate, out var qslSentDate))
        {
            fields.Add(new KeyValuePair<string, string>("QSLSDATE", qslSentDate));
        }

        if (qso.QslReceivedDate is not null && TryFormatAdifDate(qso.QslReceivedDate, out var qslReceivedDate))
        {
            fields.Add(new KeyValuePair<string, string>("QSLRDATE", qslReceivedDate));
        }

        PushConfirmationField(fields, "LOTW_QSL_SENT", qso.HasLotwSent, qso.LotwSent);
        PushConfirmationField(fields, "LOTW_QSL_RCVD", qso.HasLotwReceived, qso.LotwReceived);
        PushConfirmationField(fields, "EQSL_QSL_SENT", qso.HasEqslSent, qso.EqslSent);
        PushConfirmationField(fields, "EQSL_QSL_RCVD", qso.HasEqslReceived, qso.EqslReceived);

        AddOptionalStringField(fields, "CONTEST_ID", qso.ContestId);
        AddOptionalStringField(fields, "STX", qso.SerialSent);
        AddOptionalStringField(fields, "SRX", qso.SerialReceived);
        AddOptionalStringField(fields, "STX_STRING", qso.ExchangeSent);
        AddOptionalStringField(fields, "SRX_STRING", qso.ExchangeReceived);
        AddOptionalStringField(fields, "PROP_MODE", qso.PropMode);
        AddOptionalStringField(fields, "SAT_NAME", qso.SatName);
        AddOptionalStringField(fields, "SAT_MODE", qso.SatMode);
        AddOptionalStringField(fields, "COMMENT", qso.Comment);
        AddOptionalStringField(fields, "NOTES", qso.Notes);

        foreach (var pair in qso.ExtraFields)
        {
            if (FieldIsOverridden(qso, stationSnapshot, pair.Key))
            {
                continue;
            }

            fields.Add(new KeyValuePair<string, string>(pair.Key, pair.Value));
        }

        return fields;
    }

    private static void AppendField(StringBuilder output, string key, string value)
    {
        output.Append('<');
        output.Append(key);
        output.Append(':');
        output.Append(value.Length.ToString(CultureInfo.InvariantCulture));
        output.Append('>');
        output.Append(value);
        output.Append('\n');
    }

    private static void AddOptionalStringField(List<KeyValuePair<string, string>> fields, string key, string? value)
    {
        if (!string.IsNullOrWhiteSpace(value))
        {
            fields.Add(new KeyValuePair<string, string>(key, value));
        }
    }

    private static bool TryNormalizeModeFromAdif(string value, out Mode mode, out string? submode)
    {
        if (AdifToMode.TryGetValue(value, out mode))
        {
            submode = null;
            return true;
        }

        if (SubmodeAliases.Value.TryGetValue(value, out var alias))
        {
            mode = alias.Mode;
            submode = alias.Submode;
            return true;
        }

        mode = Mode.Unspecified;
        submode = null;
        return false;
    }

    private static RstReport ParseRstReport(string raw)
    {
        var trimmed = raw.Trim();
        return new RstReport
        {
            Readability = ParseRstDigit(trimmed, 0, 1, 5),
            Strength = ParseRstDigit(trimmed, 1, 1, 9),
            Tone = ParseRstDigit(trimmed, 2, 1, 9),
            Raw = raw,
        };
    }

    private static uint ParseRstDigit(string raw, int index, byte minimum, byte maximum)
    {
        if (index >= raw.Length || !char.IsAsciiDigit(raw[index]))
        {
            return 0;
        }

        var value = (byte)(raw[index] - '0');
        return value >= minimum && value <= maximum ? (uint)value : 0;
    }

    private static QslStatus ParseQslStatus(string value)
    {
        return value.Trim().ToUpperInvariant() switch
        {
            "Y" => QslStatus.Yes,
            "N" => QslStatus.No,
            "R" => QslStatus.Requested,
            "Q" => QslStatus.Queued,
            "I" => QslStatus.Ignore,
            _ => QslStatus.Unspecified,
        };
    }

    private static bool TryFormatQslStatus(QslStatus status, out string value)
    {
        value = status switch
        {
            QslStatus.Yes => "Y",
            QslStatus.No => "N",
            QslStatus.Requested => "R",
            QslStatus.Queued => "Q",
            QslStatus.Ignore => "I",
            _ => string.Empty,
        };

        return value.Length > 0;
    }

    private static void MapConfirmationField(QsoRecord qso, string key, string value, Action<QsoRecord, bool> setter)
    {
        if (TryParseConfirmationBool(value, out var parsed))
        {
            setter(qso, parsed);
            return;
        }

        qso.ExtraFields[key] = value;
    }

    private static bool TryParseConfirmationBool(string value, out bool parsed)
    {
        if (value.Equals("Y", StringComparison.OrdinalIgnoreCase))
        {
            parsed = true;
            return true;
        }

        if (value.Equals("N", StringComparison.OrdinalIgnoreCase))
        {
            parsed = false;
            return true;
        }

        parsed = false;
        return false;
    }

    private static void PushConfirmationField(List<KeyValuePair<string, string>> fields, string key, bool hasValue, bool value)
    {
        if (!hasValue)
        {
            return;
        }

        fields.Add(new KeyValuePair<string, string>(key, value ? "Y" : "N"));
    }

    private static bool TryParseAdifDateTime(string date, string? time, out Timestamp timestamp)
    {
        timestamp = new Timestamp();
        if (date.Length != 8 || !date.All(char.IsAscii))
        {
            return false;
        }

        if (!int.TryParse(date[..4], NumberStyles.None, CultureInfo.InvariantCulture, out var year)
            || !int.TryParse(date[4..6], NumberStyles.None, CultureInfo.InvariantCulture, out var month)
            || !int.TryParse(date[6..8], NumberStyles.None, CultureInfo.InvariantCulture, out var day))
        {
            return false;
        }

        if (time is not null && !time.All(char.IsAscii))
        {
            return false;
        }

        var hour = 0;
        var minute = 0;
        var second = 0;
        if (time is not null)
        {
            switch (time.Length)
            {
                case 4:
                    if (!int.TryParse(time[..2], NumberStyles.None, CultureInfo.InvariantCulture, out hour)
                        || !int.TryParse(time[2..4], NumberStyles.None, CultureInfo.InvariantCulture, out minute))
                    {
                        return false;
                    }

                    break;
                case 6:
                    if (!int.TryParse(time[..2], NumberStyles.None, CultureInfo.InvariantCulture, out hour)
                        || !int.TryParse(time[2..4], NumberStyles.None, CultureInfo.InvariantCulture, out minute)
                        || !int.TryParse(time[4..6], NumberStyles.None, CultureInfo.InvariantCulture, out second))
                    {
                        return false;
                    }

                    break;
            }
        }

        try
        {
            var utc = new DateTimeOffset(year, month, day, hour, minute, second, TimeSpan.Zero);
            timestamp = Timestamp.FromDateTimeOffset(utc);
            return true;
        }
        catch (ArgumentOutOfRangeException)
        {
            return false;
        }
    }

    private static bool TryFormatAdifDateTime(Timestamp timestamp, out string date, out string time)
    {
        date = string.Empty;
        time = string.Empty;
        if (!TryGetUtcDateTime(timestamp, out var dateTime))
        {
            return false;
        }

        date = dateTime.ToString("yyyyMMdd", CultureInfo.InvariantCulture);
        time = dateTime.ToString("HHmmss", CultureInfo.InvariantCulture);
        return true;
    }

    private static bool TryFormatAdifDate(Timestamp timestamp, out string date)
    {
        date = string.Empty;
        if (!TryGetUtcDateTime(timestamp, out var dateTime))
        {
            return false;
        }

        date = dateTime.ToString("yyyyMMdd", CultureInfo.InvariantCulture);
        return true;
    }

    private static bool TryGetUtcDateTime(Timestamp timestamp, out DateTimeOffset dateTime)
    {
        dateTime = default;
        if (timestamp.Nanos < 0 || timestamp.Nanos > 999_999_999)
        {
            return false;
        }

        dateTime = DateTimeOffset.FromUnixTimeSeconds(timestamp.Seconds).AddTicks(timestamp.Nanos / 100L);
        return true;
    }

    private static bool TryParseAdifLocation(string rawValue, bool latitude, out double value)
    {
        value = 0;
        var trimmed = rawValue.Trim();
        if (trimmed.Length != 11 || !trimmed.All(char.IsAscii))
        {
            return false;
        }

        var direction = char.ToUpperInvariant(trimmed[0]);
        if (latitude)
        {
            if (direction is not ('N' or 'S'))
            {
                return false;
            }
        }
        else if (direction is not ('E' or 'W'))
        {
            return false;
        }

        if (trimmed[4] != ' ')
        {
            return false;
        }

        if (!double.TryParse(trimmed.AsSpan(1, 3), NumberStyles.None, CultureInfo.InvariantCulture, out var degrees)
            || !double.TryParse(trimmed.AsSpan(5, 6), NumberStyles.AllowDecimalPoint, CultureInfo.InvariantCulture, out var minutes))
        {
            return false;
        }

        if (minutes < 0 || minutes >= 60)
        {
            return false;
        }

        var signed = degrees + (minutes / 60.0);
        if (direction is 'S' or 'W')
        {
            signed *= -1.0;
        }

        var limit = latitude ? 90.0 : 180.0;
        if (!double.IsFinite(signed) || Math.Abs(signed) > limit)
        {
            return false;
        }

        value = signed;
        return true;
    }

    private static bool TryFormatAdifLocation(double value, bool latitude, out string formatted)
    {
        formatted = string.Empty;
        if (!double.IsFinite(value))
        {
            return false;
        }

        var limit = latitude ? 90.0 : 180.0;
        if (Math.Abs(value) > limit)
        {
            return false;
        }

        var direction = latitude
            ? (value < 0 ? 'S' : 'N')
            : (value < 0 ? 'W' : 'E');
        var absolute = Math.Abs(value);
        var degrees = Math.Floor(absolute);
        var minutes = Math.Round((absolute - degrees) * 60.0 * 1000.0, MidpointRounding.AwayFromZero) / 1000.0;
        if (minutes >= 60.0)
        {
            degrees += 1.0;
            minutes = 0.0;
        }

        if (degrees > limit)
        {
            return false;
        }

        formatted = string.Format(CultureInfo.InvariantCulture, "{0}{1:000} {2:000.000}", direction, degrees, minutes);
        return true;
    }

    private static bool TryConvertMhzToKhz(double mhz, out ulong khz)
    {
        khz = 0;
        if (!double.IsFinite(mhz) || mhz < 0)
        {
            return false;
        }

        var rounded = Math.Round(mhz * 1000.0, MidpointRounding.AwayFromZero);
        if (rounded < 0 || rounded > ulong.MaxValue)
        {
            return false;
        }

        khz = (ulong)rounded;
        return true;
    }

    private static void EnrichFromDxcc(QsoRecord qso)
    {
        if (!qso.HasWorkedDxcc || !DxccEntities.Value.TryGetValue(qso.WorkedDxcc, out var entity))
        {
            return;
        }

        if (string.IsNullOrWhiteSpace(qso.WorkedCountry))
        {
            qso.WorkedCountry = entity.Country;
        }

        if (string.IsNullOrWhiteSpace(qso.WorkedContinent) && !string.IsNullOrEmpty(entity.Continent))
        {
            qso.WorkedContinent = entity.Continent;
        }

        if (!qso.HasWorkedCqZone && entity.CqZone is { } cqZone)
        {
            qso.WorkedCqZone = cqZone;
        }

        if (!qso.HasWorkedItuZone && entity.ItuZone is { } ituZone)
        {
            qso.WorkedItuZone = ituZone;
        }
    }

    private static bool FieldIsOverridden(QsoRecord qso, StationSnapshot? stationSnapshot, string key)
    {
        return key.Equals("LOTW_QSL_SENT", StringComparison.OrdinalIgnoreCase) ? qso.HasLotwSent
            : key.Equals("LOTW_QSL_RCVD", StringComparison.OrdinalIgnoreCase) ? qso.HasLotwReceived
            : key.Equals("EQSL_QSL_SENT", StringComparison.OrdinalIgnoreCase) ? qso.HasEqslSent
            : key.Equals("EQSL_QSL_RCVD", StringComparison.OrdinalIgnoreCase) ? qso.HasEqslReceived
            : key.Equals("STATION_CALLSIGN", StringComparison.OrdinalIgnoreCase) ? !string.IsNullOrEmpty(stationSnapshot?.StationCallsign ?? qso.StationCallsign)
            : key.Equals("OPERATOR", StringComparison.OrdinalIgnoreCase) ? !string.IsNullOrWhiteSpace(stationSnapshot?.OperatorCallsign)
            : key.Equals("CONTACTED_OP", StringComparison.OrdinalIgnoreCase) ? !string.IsNullOrWhiteSpace(qso.WorkedOperatorCallsign)
            : key.Equals("ARRL_SECT", StringComparison.OrdinalIgnoreCase) ? !string.IsNullOrWhiteSpace(qso.WorkedArrlSection)
            : key.Equals("SKCC", StringComparison.OrdinalIgnoreCase) ? !string.IsNullOrWhiteSpace(qso.Skcc)
            : key.Equals("MY_NAME", StringComparison.OrdinalIgnoreCase) ? !string.IsNullOrWhiteSpace(stationSnapshot?.OperatorName)
            : key.Equals("MY_GRIDSQUARE", StringComparison.OrdinalIgnoreCase) ? !string.IsNullOrWhiteSpace(stationSnapshot?.Grid)
            : key.Equals("MY_CNTY", StringComparison.OrdinalIgnoreCase) ? !string.IsNullOrWhiteSpace(stationSnapshot?.County)
            : key.Equals("MY_STATE", StringComparison.OrdinalIgnoreCase) ? !string.IsNullOrWhiteSpace(stationSnapshot?.State)
            : key.Equals("MY_COUNTRY", StringComparison.OrdinalIgnoreCase) ? !string.IsNullOrWhiteSpace(stationSnapshot?.Country)
            : key.Equals("MY_DXCC", StringComparison.OrdinalIgnoreCase) ? stationSnapshot?.Dxcc > 0
            : key.Equals("MY_CQ_ZONE", StringComparison.OrdinalIgnoreCase) ? stationSnapshot?.CqZone > 0
            : key.Equals("MY_ITU_ZONE", StringComparison.OrdinalIgnoreCase) ? stationSnapshot?.ItuZone > 0
            : key.Equals("MY_LAT", StringComparison.OrdinalIgnoreCase) ? stationSnapshot is not null && stationSnapshot.Latitude != 0
            : key.Equals("MY_LON", StringComparison.OrdinalIgnoreCase) ? stationSnapshot is not null && stationSnapshot.Longitude != 0
            : key.Equals("MY_ARRL_SECT", StringComparison.OrdinalIgnoreCase) ? !string.IsNullOrWhiteSpace(stationSnapshot?.ArrlSection)
            : key.Equals("QSLSDATE", StringComparison.OrdinalIgnoreCase) ? qso.QslSentDate is not null && TryFormatAdifDate(qso.QslSentDate, out _)
            : key.Equals("QSLRDATE", StringComparison.OrdinalIgnoreCase) ? qso.QslReceivedDate is not null && TryFormatAdifDate(qso.QslReceivedDate, out _)
            : (key.Equals("QSO_DATE_OFF", StringComparison.OrdinalIgnoreCase) || key.Equals("TIME_OFF", StringComparison.OrdinalIgnoreCase)) && qso.UtcEndTimestamp is not null;
    }

    private static Dictionary<string, (string Submode, Mode Mode)> LoadSubmodeAliases()
    {
        using var stream = typeof(ManagedAdifCodec).Assembly.GetManifestResourceStream(SubmodeAliasesResourceName)
            ?? throw new InvalidOperationException($"Embedded resource '{SubmodeAliasesResourceName}' was not found.");
        using var reader = new StreamReader(stream, Encoding.UTF8, leaveOpen: false);

        var result = new Dictionary<string, (string Submode, Mode Mode)>(StringComparer.OrdinalIgnoreCase);
        while (reader.ReadLine() is { } line)
        {
            var parts = line.Split('\t');
            if (parts.Length != 2)
            {
                continue;
            }

            if (!AdifToMode.TryGetValue(parts[1], out var mode))
            {
                continue;
            }

            result[parts[0]] = (parts[0], mode);
        }

        return result;
    }

    private static Dictionary<uint, DxccEntityInfo> LoadDxccEntities()
    {
        using var stream = typeof(ManagedAdifCodec).Assembly.GetManifestResourceStream(DxccEntitiesResourceName)
            ?? throw new InvalidOperationException($"Embedded resource '{DxccEntitiesResourceName}' was not found.");
        using var reader = new StreamReader(stream, Encoding.UTF8, leaveOpen: false);

        var result = new Dictionary<uint, DxccEntityInfo>();
        while (reader.ReadLine() is { } line)
        {
            var parts = line.Split('\t');
            if (parts.Length < 3
                || !uint.TryParse(parts[0], NumberStyles.None, CultureInfo.InvariantCulture, out var code))
            {
                continue;
            }

            result[code] = new DxccEntityInfo(
                parts[1],
                parts[2],
                TryParseOptionalUInt32(parts.ElementAtOrDefault(3)),
                TryParseOptionalUInt32(parts.ElementAtOrDefault(4)));
        }

        return result;
    }

    private static uint? TryParseOptionalUInt32(string? value)
    {
        return uint.TryParse(value, NumberStyles.None, CultureInfo.InvariantCulture, out var parsed) ? parsed : null;
    }

    private sealed record DxccEntityInfo(string Country, string Continent, uint? CqZone, uint? ItuZone);
}
