//! ADIF adapter: parses and serializes ADIF at the engine boundary.

pub mod mapper;
mod normalize;

use crate::proto::qsoripper::domain::QsoRecord;
use difa::RecordStream;
use futures::StreamExt;
pub use mapper::AdifMapper;
use std::fmt::Write as _;

/// Parse an ADI payload into normalized `QsoRecord` values.
///
/// Header records are ignored automatically.
///
/// # Errors
///
/// Returns an error when the ADIF payload is malformed and cannot be parsed.
pub async fn parse_adi_qsos(data: &[u8]) -> Result<Vec<QsoRecord>, String> {
    let mut stream = RecordStream::new(data, true);
    let mut qsos = Vec::new();

    while let Some(result) = stream.next().await {
        let record = result.map_err(|error| error.to_string())?;
        if record.is_header() {
            continue;
        }

        qsos.push(AdifMapper::record_to_qso(&record));
    }

    Ok(qsos)
}

/// Serialize normalized `QsoRecord` values into an ADI payload.
#[must_use]
pub fn serialize_adi_qsos(qsos: &[QsoRecord], include_header: bool) -> Vec<u8> {
    let mut output = String::new();

    if include_header {
        output.push_str(&adif_header());
    }

    for qso in qsos {
        output.push_str(&AdifMapper::qso_to_adi(qso));
    }

    output.into_bytes()
}

fn adif_header() -> String {
    let mut header = String::from("Generated by QsoRipper\n");
    for (key, value) in [
        ("ADIF_VER", "3.1.7"),
        ("PROGRAMID", "QsoRipper"),
        ("PROGRAMVERSION", env!("CARGO_PKG_VERSION")),
    ] {
        let _ = writeln!(header, "<{key}:{}>{value}", value.len());
    }
    header.push_str("<EOH>\n");
    header
}

#[cfg(test)]
#[allow(clippy::expect_used, clippy::unwrap_used)]
mod tests {
    use super::{parse_adi_qsos, serialize_adi_qsos};

    #[tokio::test]
    async fn parse_adi_qsos_skips_header_records() {
        let data = include_bytes!("../../../../../tests/fixtures/basic_qsos.adi");

        let qsos = parse_adi_qsos(data).await.expect("parsed qsos");

        assert_eq!(qsos.len(), 3);
    }

    #[test]
    fn serialize_adi_qsos_can_include_header() {
        let payload = serialize_adi_qsos(&[], true);
        let text = String::from_utf8(payload).expect("utf8");

        assert!(text.contains("<ADIF_VER:5>3.1.7"));
        assert!(text.contains("<PROGRAMID:9>QsoRipper"));
        assert!(text.contains("<EOH>"));
    }
}
