<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComeFromNuGet>true</BuiltInComeFromNuGet>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\cw-scope.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <RootNamespace>CwDecoderGui</RootNamespace>
    <AssemblyName>CwDecoderGui</AssemblyName>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\cw-scope.ico" />
    <PackageReference Include="Avalonia" Version="11.3.14" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.14" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.14" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.14" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.14" Condition="'$(Configuration)' == 'Debug'" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.13" />
  </ItemGroup>

</Project>
