using System.Globalization;
using System.Text;
using Google.Protobuf.WellKnownTypes;
using QsoRipper.Domain;

namespace QsoRipper.Engine.QrzLogbook;

/// <summary>
/// ADIF parser and serializer for QRZ logbook sync.
/// Handles the <c>&lt;FIELD:LENGTH[:TYPE]&gt;VALUE</c> format and maps ADIF fields to/from <see cref="QsoRecord"/>.
/// </summary>
internal static class AdifCodec
{
    // -- Band mapping -------------------------------------------------------

    private static readonly (string Name, Band Band)[] BandTable =
    [
        ("2190M", Band._2190M), ("630M", Band._630M), ("560M", Band._560M),
        ("160M", Band._160M), ("80M", Band._80M), ("60M", Band._60M),
        ("40M", Band._40M), ("30M", Band._30M), ("20M", Band._20M),
        ("17M", Band._17M), ("15M", Band._15M), ("12M", Band._12M),
        ("10M", Band._10M), ("8M", Band._8M), ("6M", Band._6M),
        ("5M", Band._5M), ("4M", Band._4M), ("2M", Band._2M),
        ("1.25M", Band._125M), ("70CM", Band._70Cm), ("33CM", Band._33Cm),
        ("23CM", Band._23Cm), ("13CM", Band._13Cm), ("9CM", Band._9Cm),
        ("6CM", Band._6Cm), ("3CM", Band._3Cm), ("1.25CM", Band._125Cm),
        ("6MM", Band._6Mm), ("4MM", Band._4Mm), ("2.5MM", Band._25Mm),
        ("2MM", Band._2Mm), ("1MM", Band._1Mm), ("SUBMM", Band.Submm),
    ];

    private static readonly (string Name, Mode Mode)[] ModeTable =
    [
        ("AM", Mode.Am), ("ARDOP", Mode.Ardop), ("ATV", Mode.Atv),
        ("CHIP", Mode.Chip), ("CLO", Mode.Clo), ("CONTESTI", Mode.Contesti),
        ("CW", Mode.Cw), ("DIGITALVOICE", Mode.Digitalvoice), ("DOMINO", Mode.Domino),
        ("DYNAMIC", Mode.Dynamic), ("FAX", Mode.Fax), ("FM", Mode.Fm),
        ("FSK", Mode.Fsk), ("FT8", Mode.Ft8), ("HELL", Mode.Hell),
        ("ISCAT", Mode.Iscat), ("JT4", Mode.Jt4), ("JT9", Mode.Jt9),
        ("JT44", Mode.Jt44), ("JT65", Mode.Jt65), ("MFSK", Mode.Mfsk),
        ("MTONE", Mode.Mtone), ("MSK144", Mode.Msk144), ("OFDM", Mode.Ofdm),
        ("OLIVIA", Mode.Olivia), ("OPERA", Mode.Opera), ("PAC", Mode.Pac),
        ("PAX", Mode.Pax), ("PKT", Mode.Pkt), ("PSK", Mode.Psk),
        ("Q15", Mode.Q15), ("QRA64", Mode.Qra64), ("ROS", Mode.Ros),
        ("RTTY", Mode.Rtty), ("RTTYM", Mode.Rttym), ("SSB", Mode.Ssb),
        ("SSTV", Mode.Sstv), ("T10", Mode.T10), ("THOR", Mode.Thor),
        ("THRB", Mode.Thrb), ("TOR", Mode.Tor), ("V4", Mode.V4),
        ("VOI", Mode.Voi), ("WINMOR", Mode.Winmor), ("WSPR", Mode.Wspr),
    ];

    private static readonly Dictionary<string, Band> AdifToBand = BandTable.ToDictionary(
        e => e.Name, e => e.Band, StringComparer.OrdinalIgnoreCase);

    private static readonly Dictionary<Band, string> BandToAdif = BandTable.ToDictionary(
        e => e.Band, e => e.Name);

    private static readonly Dictionary<string, Mode> AdifToMode = ModeTable.ToDictionary(
        e => e.Name, e => e.Mode, StringComparer.OrdinalIgnoreCase);

    private static readonly Dictionary<Mode, string> ModeToAdif = ModeTable.ToDictionary(
        e => e.Mode, e => e.Name);

    // -- Parsing ------------------------------------------------------------

    /// <summary>
    /// Parse ADIF text into a list of <see cref="QsoRecord"/> instances.
    /// Skips the header (content before <c>&lt;EOH&gt;</c>) and collects records
    /// delimited by <c>&lt;EOR&gt;</c>.
    /// </summary>
    internal static List<QsoRecord> ParseAdif(string text)
    {
        var records = ParseRawRecords(text);
        var qsos = new List<QsoRecord>(records.Count);
        foreach (var record in records)
        {
            qsos.Add(MapRecordToQso(record));
        }

        return qsos;
    }

    /// <summary>
    /// Serialize a single <see cref="QsoRecord"/> as an ADIF record string (no header, includes <c>&lt;eor&gt;</c>).
    /// Used for QRZ INSERT payloads.
    /// </summary>
    internal static string SerializeSingleQso(QsoRecord qso)
    {
        var sb = new StringBuilder(512);
        WriteAdifFields(sb, qso);
        sb.Append("<eor>\n");
        return sb.ToString();
    }

    /// <summary>
    /// Serialize multiple QSOs with an optional ADIF header.
    /// </summary>
    internal static byte[] SerializeAdif(IEnumerable<QsoRecord> qsos, bool includeHeader)
    {
        var sb = new StringBuilder();
        if (includeHeader)
        {
            sb.Append("Generated by QsoRipper\n");
            AppendField(sb, "ADIF_VER", "3.1.7");
            AppendField(sb, "PROGRAMID", "QsoRipper");
            sb.Append("<EOH>\n");
        }

        foreach (var qso in qsos)
        {
            WriteAdifFields(sb, qso);
            sb.Append("<eor>\n");
        }

        return Encoding.UTF8.GetBytes(sb.ToString());
    }

    // -- Raw ADIF record parsing --------------------------------------------

    private static List<Dictionary<string, string>> ParseRawRecords(string text)
    {
        var records = new List<Dictionary<string, string>>();
        var current = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        var inHeader = text.Contains("<EOH>", StringComparison.OrdinalIgnoreCase);
        var index = 0;

        while (index < text.Length)
        {
            var tagStart = text.IndexOf('<', index);
            if (tagStart < 0)
            {
                break;
            }

            var tagEnd = text.IndexOf('>', tagStart + 1);
            if (tagEnd < 0)
            {
                break; // Tolerant: don't throw on unterminated tags from QRZ
            }

            var rawTag = text[(tagStart + 1)..tagEnd].Trim();
            index = tagEnd + 1;
            if (rawTag.Length == 0)
            {
                continue;
            }

            if (rawTag.Equals("EOH", StringComparison.OrdinalIgnoreCase))
            {
                inHeader = false;
                current.Clear();
                continue;
            }

            if (rawTag.Equals("EOR", StringComparison.OrdinalIgnoreCase))
            {
                if (!inHeader && current.Count > 0)
                {
                    records.Add(current);
                    current = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                }

                continue;
            }

            var colonIndex = rawTag.AsSpan().IndexOf(':');
            if (colonIndex < 0)
            {
                continue; // Tolerant: skip malformed tags
            }

            var key = rawTag[..colonIndex].Trim();
            if (key.Length == 0)
            {
                continue;
            }

            var lengthPart = rawTag[(colonIndex + 1)..];
            var typeSeparator = lengthPart.AsSpan().IndexOf(':');
            if (typeSeparator >= 0)
            {
                lengthPart = lengthPart[..typeSeparator];
            }

            if (!int.TryParse(lengthPart, NumberStyles.None, CultureInfo.InvariantCulture, out var valueLength) || valueLength < 0)
            {
                continue; // Tolerant: skip unparseable lengths
            }

            if (index + valueLength > text.Length)
            {
                break; // Tolerant: truncated payload
            }

            var value = text.Substring(index, valueLength);
            index += valueLength;

            if (!inHeader)
            {
                current[key.ToUpperInvariant()] = value;
            }
        }

        // Discard incomplete trailing record (no <eor>).
        return records;
    }

    // -- Field mapping: ADIF → QsoRecord ------------------------------------

    private static QsoRecord MapRecordToQso(IReadOnlyDictionary<string, string> record)
    {
        var qso = new QsoRecord
        {
            LocalId = Guid.NewGuid().ToString(),
            SyncStatus = SyncStatus.LocalOnly,
        };
        StationSnapshot? stationSnapshot = null;
        string? qsoDate = null;
        string? timeOn = null;
        string? qsoDateOff = null;
        string? timeOff = null;

        foreach (var pair in record)
        {
            var key = pair.Key.ToUpperInvariant();
            var value = pair.Value;

            switch (key)
            {
                case "CALL":
                    qso.WorkedCallsign = value;
                    break;
                case "STATION_CALLSIGN":
                    qso.StationCallsign = value;
                    (stationSnapshot ??= new StationSnapshot()).StationCallsign = value;
                    break;
                case "OPERATOR":
                    (stationSnapshot ??= new StationSnapshot()).OperatorCallsign = value;
                    if (string.IsNullOrWhiteSpace(qso.StationCallsign))
                    {
                        qso.StationCallsign = value;
                        (stationSnapshot ??= new StationSnapshot()).StationCallsign = value;
                    }

                    break;
                case "QSO_DATE":
                    qsoDate = value;
                    break;
                case "TIME_ON":
                    timeOn = value;
                    break;
                case "QSO_DATE_OFF":
                    qsoDateOff = value;
                    break;
                case "TIME_OFF":
                    timeOff = value;
                    break;
                case "BAND":
                    if (AdifToBand.TryGetValue(value, out var band))
                    {
                        qso.Band = band;
                    }
                    else
                    {
                        qso.ExtraFields[key] = value;
                    }

                    break;
                case "MODE":
                    if (AdifToMode.TryGetValue(value, out var mode))
                    {
                        qso.Mode = mode;
                    }
                    else
                    {
                        qso.ExtraFields[key] = value;
                    }

                    break;
                case "SUBMODE":
                    qso.Submode = value;
                    break;
                case "FREQ":
                    if (double.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out var mhz)
                        && TryConvertMhzToKhz(mhz, out var khz))
                    {
                        qso.FrequencyKhz = khz;
                    }
                    else
                    {
                        qso.ExtraFields[key] = value;
                    }

                    break;
                case "RST_SENT":
                    qso.RstSent = ParseRstReport(value);
                    break;
                case "RST_RCVD":
                    qso.RstReceived = ParseRstReport(value);
                    break;
                case "TX_PWR":
                    qso.TxPower = value;
                    break;
                case "CONTACTED_OP":
                    qso.WorkedOperatorCallsign = value;
                    break;
                case "NAME":
                    qso.WorkedOperatorName = value;
                    break;
                case "GRIDSQUARE":
                    qso.WorkedGrid = value;
                    break;
                case "COUNTRY":
                    qso.WorkedCountry = value;
                    break;
                case "DXCC":
                    if (uint.TryParse(value, NumberStyles.None, CultureInfo.InvariantCulture, out var dxcc))
                    {
                        qso.WorkedDxcc = dxcc;
                    }

                    break;
                case "STATE":
                    qso.WorkedState = value;
                    break;
                case "CNTY":
                    qso.WorkedCounty = value;
                    break;
                case "CONT":
                    qso.WorkedContinent = value;
                    break;
                case "CQZ":
                    if (uint.TryParse(value, NumberStyles.None, CultureInfo.InvariantCulture, out var cqZone))
                    {
                        qso.WorkedCqZone = cqZone;
                    }

                    break;
                case "ITUZ":
                    if (uint.TryParse(value, NumberStyles.None, CultureInfo.InvariantCulture, out var ituZone))
                    {
                        qso.WorkedItuZone = ituZone;
                    }

                    break;
                case "IOTA":
                    qso.WorkedIota = value;
                    break;
                case "MY_NAME":
                    (stationSnapshot ??= new StationSnapshot()).OperatorName = value;
                    break;
                case "MY_GRIDSQUARE":
                    (stationSnapshot ??= new StationSnapshot()).Grid = value;
                    break;
                case "MY_CNTY":
                    (stationSnapshot ??= new StationSnapshot()).County = value;
                    break;
                case "MY_STATE":
                    (stationSnapshot ??= new StationSnapshot()).State = value;
                    break;
                case "MY_COUNTRY":
                    (stationSnapshot ??= new StationSnapshot()).Country = value;
                    break;
                case "MY_DXCC":
                    if (uint.TryParse(value, NumberStyles.None, CultureInfo.InvariantCulture, out var myDxcc))
                    {
                        (stationSnapshot ??= new StationSnapshot()).Dxcc = myDxcc;
                    }
                    else
                    {
                        qso.ExtraFields[key] = value;
                    }

                    break;
                case "CONTEST_ID":
                    qso.ContestId = value;
                    break;
                case "SRX":
                    qso.SerialReceived = value;
                    break;
                case "STX":
                    qso.SerialSent = value;
                    break;
                case "SRX_STRING":
                    qso.ExchangeReceived = value;
                    break;
                case "STX_STRING":
                    qso.ExchangeSent = value;
                    break;
                case "PROP_MODE":
                    qso.PropMode = value;
                    break;
                case "SAT_NAME":
                    qso.SatName = value;
                    break;
                case "SAT_MODE":
                    qso.SatMode = value;
                    break;
                case "COMMENT":
                    qso.Comment = value;
                    break;
                case "NOTES":
                    qso.Notes = value;
                    break;
                // QRZ-specific ADIF application fields
                case "APP_QRZLOG_LOGID":
                case "APP_QRZ_LOGID":
                    qso.QrzLogid = value;
                    break;
                case "APP_QRZLOG_QSO_ID":
                    qso.QrzBookid = value;
                    break;
                default:
                    qso.ExtraFields[key] = value;
                    break;
            }
        }

        // Compose timestamps from date + time parts.
        if (qsoDate is not null && TryParseAdifDateTime(qsoDate, timeOn, out var utcTimestamp))
        {
            qso.UtcTimestamp = utcTimestamp;
        }

        if (timeOff is not null || qsoDateOff is not null)
        {
            var endDate = qsoDateOff ?? qsoDate;
            if (endDate is not null && TryParseAdifDateTime(endDate, timeOff, out var endTimestamp))
            {
                qso.UtcEndTimestamp = endTimestamp;
            }
        }

        if (stationSnapshot is not null)
        {
            qso.StationSnapshot = stationSnapshot;
        }

        return qso;
    }

    // -- Field mapping: QsoRecord → ADIF ------------------------------------

    private static void WriteAdifFields(StringBuilder sb, QsoRecord qso)
    {
        if (!string.IsNullOrEmpty(qso.StationCallsign))
        {
            AppendField(sb, "STATION_CALLSIGN", qso.StationCallsign);
        }

        if (!string.IsNullOrEmpty(qso.WorkedCallsign))
        {
            AppendField(sb, "CALL", qso.WorkedCallsign);
        }

        if (qso.UtcTimestamp is not null && TryFormatAdifDateTime(qso.UtcTimestamp, out var date, out var time))
        {
            AppendField(sb, "QSO_DATE", date);
            AppendField(sb, "TIME_ON", time);
        }

        if (qso.UtcEndTimestamp is not null && TryFormatAdifDateTime(qso.UtcEndTimestamp, out var endDate, out var endTime))
        {
            AppendField(sb, "QSO_DATE_OFF", endDate);
            AppendField(sb, "TIME_OFF", endTime);
        }

        if (BandToAdif.TryGetValue(qso.Band, out var bandStr))
        {
            AppendField(sb, "BAND", bandStr);
        }

        if (ModeToAdif.TryGetValue(qso.Mode, out var modeStr))
        {
            AppendField(sb, "MODE", modeStr);
        }

        if (qso.HasSubmode && !string.IsNullOrWhiteSpace(qso.Submode))
        {
            AppendField(sb, "SUBMODE", qso.Submode);
        }

        if (qso.HasFrequencyKhz)
        {
            AppendField(sb, "FREQ", $"{qso.FrequencyKhz / 1000}.{qso.FrequencyKhz % 1000:000}");
        }

        if (qso.RstSent is not null)
        {
            AppendField(sb, "RST_SENT", qso.RstSent.Raw);
        }

        if (qso.RstReceived is not null)
        {
            AppendField(sb, "RST_RCVD", qso.RstReceived.Raw);
        }

        AppendOptional(sb, "TX_PWR", qso.TxPower);
        AppendOptional(sb, "CONTACTED_OP", qso.WorkedOperatorCallsign);
        AppendOptional(sb, "NAME", qso.WorkedOperatorName);
        AppendOptional(sb, "GRIDSQUARE", qso.WorkedGrid);
        AppendOptional(sb, "COUNTRY", qso.WorkedCountry);

        if (qso.HasWorkedDxcc)
        {
            AppendField(sb, "DXCC", qso.WorkedDxcc.ToString(CultureInfo.InvariantCulture));
        }

        AppendOptional(sb, "STATE", qso.WorkedState);
        AppendOptional(sb, "CNTY", qso.WorkedCounty);
        AppendOptional(sb, "CONT", qso.WorkedContinent);

        if (qso.HasWorkedCqZone)
        {
            AppendField(sb, "CQZ", qso.WorkedCqZone.ToString(CultureInfo.InvariantCulture));
        }

        if (qso.HasWorkedItuZone)
        {
            AppendField(sb, "ITUZ", qso.WorkedItuZone.ToString(CultureInfo.InvariantCulture));
        }

        AppendOptional(sb, "IOTA", qso.WorkedIota);
        AppendOptional(sb, "CONTEST_ID", qso.ContestId);
        AppendOptional(sb, "STX", qso.SerialSent);
        AppendOptional(sb, "SRX", qso.SerialReceived);
        AppendOptional(sb, "STX_STRING", qso.ExchangeSent);
        AppendOptional(sb, "SRX_STRING", qso.ExchangeReceived);
        AppendOptional(sb, "PROP_MODE", qso.PropMode);
        AppendOptional(sb, "SAT_NAME", qso.SatName);
        AppendOptional(sb, "SAT_MODE", qso.SatMode);
        AppendOptional(sb, "COMMENT", qso.Comment);
        AppendOptional(sb, "NOTES", qso.Notes);

        // Station snapshot fields
        if (qso.StationSnapshot is { } snap)
        {
            AppendOptional(sb, "MY_NAME", snap.OperatorName);
            AppendOptional(sb, "MY_GRIDSQUARE", snap.Grid);
            AppendOptional(sb, "MY_CNTY", snap.County);
            AppendOptional(sb, "MY_STATE", snap.State);
            AppendOptional(sb, "MY_COUNTRY", snap.Country);
        }

        // Round-trip: emit any extra fields the parser didn't map.
        foreach (var extra in qso.ExtraFields)
        {
            AppendField(sb, extra.Key, extra.Value);
        }
    }

    // -- Helpers -------------------------------------------------------------

    private static void AppendField(StringBuilder sb, string key, string value)
    {
        sb.Append('<');
        sb.Append(key);
        sb.Append(':');
        sb.Append(value.Length.ToString(CultureInfo.InvariantCulture));
        sb.Append('>');
        sb.Append(value);
        sb.Append('\n');
    }

    private static void AppendOptional(StringBuilder sb, string key, string? value)
    {
        if (!string.IsNullOrWhiteSpace(value))
        {
            AppendField(sb, key, value);
        }
    }

    private static bool TryParseAdifDateTime(string date, string? time, out Timestamp timestamp)
    {
        timestamp = new Timestamp();
        if (date.Length < 8)
        {
            return false;
        }

        if (!int.TryParse(date.AsSpan(0, 4), NumberStyles.None, CultureInfo.InvariantCulture, out var year)
            || !int.TryParse(date.AsSpan(4, 2), NumberStyles.None, CultureInfo.InvariantCulture, out var month)
            || !int.TryParse(date.AsSpan(6, 2), NumberStyles.None, CultureInfo.InvariantCulture, out var day))
        {
            return false;
        }

        int hour = 0, minute = 0, second = 0;
        if (time is not null && time.Length >= 4)
        {
            int.TryParse(time.AsSpan(0, 2), NumberStyles.None, CultureInfo.InvariantCulture, out hour);
            int.TryParse(time.AsSpan(2, 2), NumberStyles.None, CultureInfo.InvariantCulture, out minute);
            if (time.Length >= 6)
            {
                int.TryParse(time.AsSpan(4, 2), NumberStyles.None, CultureInfo.InvariantCulture, out second);
            }
        }

        try
        {
            var dt = new DateTimeOffset(year, month, day, hour, minute, second, TimeSpan.Zero);
            timestamp = Timestamp.FromDateTimeOffset(dt);
            return true;
        }
        catch (ArgumentOutOfRangeException)
        {
            return false;
        }
    }

    private static bool TryFormatAdifDateTime(Timestamp ts, out string date, out string time)
    {
        date = string.Empty;
        time = string.Empty;
        try
        {
            var dt = ts.ToDateTimeOffset();
            date = dt.ToString("yyyyMMdd", CultureInfo.InvariantCulture);
            time = dt.ToString("HHmmss", CultureInfo.InvariantCulture);
            return true;
        }
        catch (InvalidOperationException)
        {
            return false;
        }
    }

    private static bool TryConvertMhzToKhz(double mhz, out ulong khz)
    {
        khz = 0;
        if (mhz <= 0)
        {
            return false;
        }

        khz = (ulong)Math.Round(mhz * 1000, MidpointRounding.AwayFromZero);
        return true;
    }

    private static RstReport ParseRstReport(string raw)
    {
        var trimmed = raw.Trim();
        return new RstReport
        {
            Readability = ParseRstDigit(trimmed, 0, 1, 5),
            Strength = ParseRstDigit(trimmed, 1, 1, 9),
            Tone = ParseRstDigit(trimmed, 2, 1, 9),
            Raw = raw,
        };
    }

    private static uint ParseRstDigit(string raw, int index, byte minimum, byte maximum)
    {
        if (index >= raw.Length || !char.IsAsciiDigit(raw[index]))
        {
            return 0;
        }

        var value = (byte)(raw[index] - '0');
        return value >= minimum && value <= maximum ? (uint)value : 0;
    }
}
