using Google.Protobuf;
using Google.Protobuf.WellKnownTypes;
using LogRipper.Domain;
using LogRipper.DebugHost.Models;

namespace LogRipper.DebugHost.Services;

public sealed class SampleProtoFactory
{
    public LookupRequest CreateLookupRequest(string callsign, bool skipCache = false)
    {
        return new LookupRequest
        {
            Callsign = NormalizeCallsign(callsign),
            SkipCache = skipCache
        };
    }

    public CallsignRecord CreateCallsignRecord(string callsign)
    {
        var normalizedCallsign = NormalizeCallsign(callsign);
        return new CallsignRecord
        {
            Callsign = normalizedCallsign,
            CrossRef = normalizedCallsign,
            FirstName = "Taylor",
            LastName = "Operator",
            FormattedName = "Taylor Operator",
            Addr2 = "Seattle",
            State = "WA",
            Country = "United States",
            CountryCode = 291,
            GridSquare = "CN87up",
            GeoSource = (GeoSource)3,
            LicenseClass = "Extra",
            Eqsl = (QslPreference)1,
            Lotw = (QslPreference)1,
            PaperQsl = (QslPreference)2,
            CqZone = 3,
            ItuZone = 6,
            DxccCountryName = "United States",
            DxccContinent = "NA",
            QrzSerial = 1234567,
            LastModified = Timestamp.FromDateTime(DateTime.SpecifyKind(DateTime.UtcNow.AddDays(-2), DateTimeKind.Utc))
        };
    }

    public LookupResult CreateLookupResult(string callsign, bool cacheHit = true)
    {
        var normalizedCallsign = NormalizeCallsign(callsign);
        return new LookupResult
        {
            State = (LookupState)1,
            Record = CreateCallsignRecord(normalizedCallsign),
            CacheHit = cacheHit,
            LookupLatencyMs = 42,
            QueriedCallsign = normalizedCallsign
        };
    }

    public QsoRecord CreateQsoRecord(string workedCallsign)
    {
        return CreateQsoRecord(workedCallsign, new QsoSampleOptions());
    }

    public QsoRecord CreateQsoRecord(string workedCallsign, QsoSampleOptions options)
    {
        var utcNow = DateTime.SpecifyKind(DateTime.UtcNow, DateTimeKind.Utc);
        var normalizedCallsign = NormalizeCallsign(workedCallsign);
        var sampleRst = CreateSampleRst(options.Mode);
        var frequencyKhz = GetSampleFrequencyKhz(options.Band);
        var submode = GetSampleSubmode(options.Band, options.Mode);
        var record = new QsoRecord
        {
            LocalId = Guid.NewGuid().ToString("D"),
            StationCallsign = "K7DBG",
            WorkedCallsign = normalizedCallsign,
            UtcTimestamp = Timestamp.FromDateTime(utcNow),
            Band = options.Band,
            Mode = options.Mode,
            FrequencyKhz = frequencyKhz,
            RstSent = sampleRst.Sent,
            RstReceived = sampleRst.Received,
            TxPower = "100",
            WorkedOperatorName = "Taylor Operator",
            WorkedGrid = "CN87up",
            WorkedCountry = "United States",
            WorkedDxcc = 291,
            WorkedContinent = "NA",
            Notes = "Generated by the debug workbench.",
            Comment = "Sample QSO payload",
            CreatedAt = Timestamp.FromDateTime(utcNow),
            UpdatedAt = Timestamp.FromDateTime(utcNow),
            SyncStatus = (SyncStatus)0
        };

        if (!string.IsNullOrWhiteSpace(submode))
        {
            record.Submode = submode;
        }

        return record;
    }

    public DxccEntity CreateDxccEntity()
    {
        return new DxccEntity
        {
            DxccCode = 291,
            CountryName = "United States",
            Continent = "NA",
            ItuZone = 6,
            CqZone = 3,
            UtcOffset = -8,
            Latitude = 47.6062,
            Longitude = -122.3321,
            Notes = "Sample DXCC entity for the debug workbench."
        };
    }

    public IMessage CreateSampleMessage(SampleMessageType sampleType, string callsign, QsoSampleOptions? qsoOptions = null)
    {
        return sampleType switch
        {
            SampleMessageType.LookupRequest => CreateLookupRequest(callsign),
            SampleMessageType.LookupResult => CreateLookupResult(callsign),
            SampleMessageType.CallsignRecord => CreateCallsignRecord(callsign),
            SampleMessageType.QsoRecord => CreateQsoRecord(callsign, qsoOptions ?? new QsoSampleOptions()),
            SampleMessageType.DxccEntity => CreateDxccEntity(),
            _ => CreateLookupRequest(callsign)
        };
    }

    private static (RstReport Sent, RstReport Received) CreateSampleRst(Mode mode)
    {
        return mode switch
        {
            Mode.Cw => (
                new RstReport { Raw = "599", Readability = 5, Strength = 9, Tone = 9 },
                new RstReport { Raw = "579", Readability = 5, Strength = 7, Tone = 9 }),
            Mode.Ft8 or Mode.Rtty or Mode.Psk or Mode.Mfsk => (
                new RstReport { Raw = "-08" },
                new RstReport { Raw = "-12" }),
            _ => (
                new RstReport { Raw = "59", Readability = 5, Strength = 9 },
                new RstReport { Raw = "57", Readability = 5, Strength = 7 })
        };
    }

    private static ulong GetSampleFrequencyKhz(Band band)
    {
        return band switch
        {
            Band._160M => 1900,
            Band._80M => 3900,
            Band._40M => 7100,
            Band._30M => 10136,
            Band._20M => 14250,
            Band._17M => 18100,
            Band._15M => 21250,
            Band._12M => 24940,
            Band._10M => 28400,
            Band._6M => 50125,
            Band._2M => 146520,
            Band._70Cm => 446000,
            _ => 14250
        };
    }

    private static string? GetSampleSubmode(Band band, Mode mode)
    {
        return mode switch
        {
            Mode.Ssb => band is Band._160M or Band._80M or Band._40M ? "LSB" : "USB",
            Mode.Ft8 => "FT8",
            _ => null
        };
    }

    private static string NormalizeCallsign(string? callsign)
    {
        return string.IsNullOrWhiteSpace(callsign)
            ? "K7DBG"
            : callsign.Trim().ToUpperInvariant();
    }
}
