using System.Security.Cryptography;
using Google.Protobuf.Reflection;
using LogRipper.DebugHost.Models;
using LogRipper.Domain;

namespace LogRipper.DebugHost.Services;

internal sealed class SampleGenerationContext
{
    private static readonly SampleStationTemplate[] StationTemplates =
    [
        new(
            ProfileLabel: "Home",
            ProfileSlug: "home",
            StationCallsign: "K7DBG",
            OperatorCallsign: "K7DBG",
            Grid: "CN87up",
            County: "KING",
            State: "WA",
            Country: "United States",
            Continent: "NA",
            Dxcc: 291,
            CqZone: 3,
            ItuZone: 6,
            Latitude: 47.6062,
            Longitude: -122.3321,
            City: "Seattle"),
        new(
            ProfileLabel: "Portable",
            ProfileSlug: "portable",
            StationCallsign: "K7DBG/P",
            OperatorCallsign: "K7DBG",
            Grid: "CN85ql",
            County: "LANE",
            State: "OR",
            Country: "United States",
            Continent: "NA",
            Dxcc: 291,
            CqZone: 3,
            ItuZone: 6,
            Latitude: 44.0521,
            Longitude: -123.0868,
            City: "Eugene"),
        new(
            ProfileLabel: "Field Day",
            ProfileSlug: "field-day",
            StationCallsign: "W7FD",
            OperatorCallsign: "W7FD",
            Grid: "DN17nu",
            County: "ADA",
            State: "ID",
            Country: "United States",
            Continent: "NA",
            Dxcc: 291,
            CqZone: 4,
            ItuZone: 7,
            Latitude: 43.6150,
            Longitude: -116.2023,
            City: "Boise"),
        new(
            ProfileLabel: "Rover",
            ProfileSlug: "rover",
            StationCallsign: "K6RVR",
            OperatorCallsign: "K6RVR",
            Grid: "DM04wc",
            County: "LOS ANGELES",
            State: "CA",
            Country: "United States",
            Continent: "NA",
            Dxcc: 291,
            CqZone: 3,
            ItuZone: 6,
            Latitude: 34.1478,
            Longitude: -118.1445,
            City: "Pasadena"),
        new(
            ProfileLabel: "Summit",
            ProfileSlug: "summit",
            StationCallsign: "N0SOTA",
            OperatorCallsign: "N0SOTA",
            Grid: "DM79lt",
            County: "JEFFERSON",
            State: "CO",
            Country: "United States",
            Continent: "NA",
            Dxcc: 291,
            CqZone: 4,
            ItuZone: 7,
            Latitude: 39.7555,
            Longitude: -105.2211,
            City: "Golden")
    ];

    private static readonly string[] FirstNames =
    [
        "Taylor",
        "Jordan",
        "Casey",
        "Riley",
        "Avery",
        "Morgan",
        "Cameron",
        "Harper"
    ];

    private static readonly string[] LastNames =
    [
        "Treit",
        "Rivera",
        "Nguyen",
        "Miller",
        "Fischer",
        "Brooks",
        "Patel",
        "Walker"
    ];

    private static readonly string[] NoteTemplates =
    [
        "Generated by the debug workbench during a sample portable run.",
        "Sample operator note for a quick station profile preview.",
        "Mock payload showing realistic station defaults for local logging.",
        "Synthetic payload for exercising protobuf contracts end-to-end."
    ];

    private static readonly string[] CommentTemplates =
    [
        "Sample comment for the debug workbench.",
        "Portable setup preview generated for contract inspection.",
        "Synthetic payload for a realistic operator workflow.",
        "Mock data for testing gRPC message shape."
    ];

    private static readonly string[] SummaryTemplates =
    [
        "Sample runtime snapshot generated for inspection.",
        "Synthetic setup/profile payload for the debug bench.",
        "Fresh protobuf sample for the selected contract.",
        "Generated sample payload with realistic station context."
    ];

    private static readonly string[] WarningTemplates =
    [
        "Sample warning: session override is active for this generated payload.",
        "Sample warning: setup uses a mock credential pair for preview only.",
        "Sample warning: this payload is synthetic and not persisted.",
        "Sample warning: generated values may differ on the next run."
    ];

    private static readonly string[] ErrorTemplates =
    [
        "Sample error payload for contract inspection.",
        "Synthetic configuration warning for preview purposes.",
        "Generated validation message for the debug workbench.",
        "Mock transport error used to populate sample fields."
    ];

    private static readonly string[] PowerLevels =
    [
        "5",
        "10",
        "20",
        "50",
        "100",
        "400"
    ];

    private SampleGenerationContext(
        string inputCallsign,
        QsoSampleOptions options,
        SampleStationTemplate station,
        string generationToken,
        string firstName,
        string lastName)
    {
        InputCallsign = inputCallsign;
        Options = options;
        Station = station;
        GenerationToken = generationToken;

        var profileSuffix = NextInt(11, 99);
        ProfileId = $"{station.ProfileSlug}-{profileSuffix}-{generationToken[..4]}";
        ProfileName = station.ProfileLabel;
        FirstName = firstName;
        LastName = lastName;
        OperatorName = $"{firstName} {lastName}";
        GeneratedAtUtc = DateTime.SpecifyKind(DateTime.UtcNow.AddMinutes(-NextInt(1, 180)), DateTimeKind.Utc);
        UpdatedAtUtc = GeneratedAtUtc.AddMinutes(NextInt(1, 45));
        LastModifiedUtc = GeneratedAtUtc.AddDays(-NextInt(1, 7));
        SkipCache = NextBool();
        CacheHit = !SkipCache || NextInt(0, 3) != 0;
        MakeActive = NextBool();
        HasSessionOverride = NextBool();
        SetupComplete = true;
        PreferSqlite = NextInt(0, 4) != 0;
        SessionKey = $"sample-{generationToken[..10]}";
        UserAgent = $"LogRipper/0.1.0 ({station.OperatorCallsign})";
        SqlitePath = $".\\data\\{station.ProfileSlug}-{GeneratedAtUtc:yyyyMMdd-HHmm}.db";
        LocalId = Guid.NewGuid().ToString("D");
        Comment = Pick(CommentTemplates);
        Note = Pick(NoteTemplates);
        Summary = Pick(SummaryTemplates);
        Warning = Pick(WarningTemplates);
        ErrorMessage = Pick(ErrorTemplates);
        Addr2 = station.City;
        LicenseClass = Pick(["Extra", "Advanced", "General", "Amateur Extra"]);
        TxPower = Pick(PowerLevels);
        LookupLatencyMs = NextInt(18, 250);
        HttpTimeoutSeconds = NextInt(5, 16);
        MaxRetries = NextInt(1, 4);
        QrzSerial = NextInt(100000, 9999999);
        Count = NextInt(1, 4);
        NegativeOffsetHours = -NextInt(5, 9);
        Latitude = station.Latitude + NextDouble(-0.08, 0.08);
        Longitude = station.Longitude + NextDouble(-0.08, 0.08);
    }

    public string InputCallsign { get; }

    public QsoSampleOptions Options { get; }

    public SampleStationTemplate Station { get; }

    public string GenerationToken { get; }

    public string ProfileId { get; }

    public string ProfileName { get; }

    public string FirstName { get; }

    public string LastName { get; }

    public string OperatorName { get; }

    public DateTime GeneratedAtUtc { get; }

    public DateTime UpdatedAtUtc { get; }

    public DateTime LastModifiedUtc { get; }

    public bool SkipCache { get; }

    public bool CacheHit { get; }

    public bool MakeActive { get; }

    public bool HasSessionOverride { get; }

    public bool SetupComplete { get; }

    public bool PreferSqlite { get; }

    public string SessionKey { get; }

    public string UserAgent { get; }

    public string SqlitePath { get; }

    public string LocalId { get; }

    public string Comment { get; }

    public string Note { get; }

    public string Summary { get; }

    public string Warning { get; }

    public string ErrorMessage { get; }

    public string Addr2 { get; }

    public string LicenseClass { get; }

    public string TxPower { get; }

    public int LookupLatencyMs { get; }

    public int HttpTimeoutSeconds { get; }

    public int MaxRetries { get; }

    public int QrzSerial { get; }

    public int Count { get; }

    public int NegativeOffsetHours { get; }

    public double Latitude { get; }

    public double Longitude { get; }

    public static SampleGenerationContext Create(string inputCallsign, QsoSampleOptions options)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(inputCallsign);
        ArgumentNullException.ThrowIfNull(options);

        var station = StationTemplates[RandomNumberGenerator.GetInt32(StationTemplates.Length)];
        var firstName = FirstNames[RandomNumberGenerator.GetInt32(FirstNames.Length)];
        var lastName = LastNames[RandomNumberGenerator.GetInt32(LastNames.Length)];
        var generationToken = Guid.NewGuid().ToString("N");
        return new SampleGenerationContext(inputCallsign, options, station, generationToken, firstName, lastName);
    }

    public static T Pick<T>(IReadOnlyList<T> items)
    {
        ArgumentNullException.ThrowIfNull(items);

        return items[RandomNumberGenerator.GetInt32(items.Count)];
    }

    public static bool NextBool()
    {
        return RandomNumberGenerator.GetInt32(0, 2) == 0;
    }

    public static int NextInt(int minInclusive, int maxExclusive)
    {
        return RandomNumberGenerator.GetInt32(minInclusive, maxExclusive);
    }

    public static double NextDouble(double minInclusive, double maxExclusive)
    {
        var fraction = RandomNumberGenerator.GetInt32(0, 1_000_000) / 1_000_000d;
        return minInclusive + (fraction * (maxExclusive - minInclusive));
    }

    public static FieldDescriptor PickOneofField(OneofDescriptor oneof)
    {
        ArgumentNullException.ThrowIfNull(oneof);

        var fields = oneof.Fields.ToArray();
        return fields[RandomNumberGenerator.GetInt32(fields.Length)];
    }
}

internal sealed record SampleStationTemplate(
    string ProfileLabel,
    string ProfileSlug,
    string StationCallsign,
    string OperatorCallsign,
    string Grid,
    string County,
    string State,
    string Country,
    string Continent,
    int Dxcc,
    int CqZone,
    int ItuZone,
    double Latitude,
    double Longitude,
    string City);
