using Google.Protobuf;
using Google.Protobuf.WellKnownTypes;
using LogRipper.DebugHost.Models;
using LogRipper.Domain;

namespace LogRipper.DebugHost.Services;

internal sealed class SampleProtoFactory
{
    private static readonly Dictionary<System.Type, Func<SampleProtoFactory, string, QsoSampleOptions?, IMessage>> CustomBuilders =
        new Dictionary<System.Type, Func<SampleProtoFactory, string, QsoSampleOptions?, IMessage>>
        {
            [typeof(LookupRequest)] = static (factory, callsign, _) => factory.CreateLookupRequest(callsign),
            [typeof(LookupResult)] = static (factory, callsign, _) => factory.CreateLookupResult(callsign),
            [typeof(CallsignRecord)] = static (factory, callsign, _) => factory.CreateCallsignRecord(callsign),
            [typeof(StationProfile)] = static (factory, _, _) => factory.CreateStationProfile(),
            [typeof(StationSnapshot)] = static (factory, _, _) => factory.CreateStationSnapshot(),
            [typeof(QsoRecord)] = static (factory, callsign, options) => factory.CreateQsoRecord(callsign, options ?? new QsoSampleOptions()),
            [typeof(DxccEntity)] = static (factory, _, _) => factory.CreateDxccEntity()
        };

#pragma warning disable CA1822 // Mark members as static
    public LookupRequest CreateLookupRequest(string callsign, bool skipCache = false)
    {
        ArgumentNullException.ThrowIfNull(callsign);

        return new LookupRequest
        {
            Callsign = NormalizeCallsign(callsign),
            SkipCache = skipCache
        };
    }

    public CallsignRecord CreateCallsignRecord(string callsign)
    {
        ArgumentNullException.ThrowIfNull(callsign);

        var normalizedCallsign = NormalizeCallsign(callsign);
        return new CallsignRecord
        {
            Callsign = normalizedCallsign,
            CrossRef = normalizedCallsign,
            FirstName = "Taylor",
            LastName = "Operator",
            FormattedName = "Taylor Operator",
            Addr2 = "Seattle",
            State = "WA",
            Country = "United States",
            CountryCode = 291,
            GridSquare = "CN87up",
            GeoSource = (GeoSource)3,
            LicenseClass = "Extra",
            Eqsl = (QslPreference)1,
            Lotw = (QslPreference)1,
            PaperQsl = (QslPreference)2,
            CqZone = 3,
            ItuZone = 6,
            DxccCountryName = "United States",
            DxccContinent = "NA",
            QrzSerial = 1234567,
            LastModified = Timestamp.FromDateTime(DateTime.SpecifyKind(DateTime.UtcNow.AddDays(-2), DateTimeKind.Utc))
        };
    }

    public LookupResult CreateLookupResult(string callsign, bool cacheHit = true)
    {
        ArgumentNullException.ThrowIfNull(callsign);

        var normalizedCallsign = NormalizeCallsign(callsign);
        return new LookupResult
        {
            State = LookupState.Found,
            Record = CreateCallsignRecord(normalizedCallsign),
            CacheHit = cacheHit,
            LookupLatencyMs = 42,
            QueriedCallsign = normalizedCallsign
        };
    }

    public QsoRecord CreateQsoRecord(string workedCallsign)
    {
        ArgumentNullException.ThrowIfNull(workedCallsign);

        return CreateQsoRecord(workedCallsign, new QsoSampleOptions());
    }

    public QsoRecord CreateQsoRecord(string workedCallsign, QsoSampleOptions options)
    {
        ArgumentNullException.ThrowIfNull(workedCallsign);
        ArgumentNullException.ThrowIfNull(options);

        var utcNow = DateTime.SpecifyKind(DateTime.UtcNow, DateTimeKind.Utc);
        var normalizedCallsign = NormalizeCallsign(workedCallsign);
        var sampleRst = CreateSampleRst(options.Mode);
        var frequencyKhz = GetSampleFrequencyKhz(options.Band);
        var submode = GetSampleSubmode(options.Band, options.Mode);
        var record = new QsoRecord
        {
            LocalId = Guid.NewGuid().ToString("D"),
            StationCallsign = "K7DBG",
            WorkedCallsign = normalizedCallsign,
            UtcTimestamp = Timestamp.FromDateTime(utcNow),
            Band = options.Band,
            Mode = options.Mode,
            FrequencyKhz = frequencyKhz,
            RstSent = sampleRst.Sent,
            RstReceived = sampleRst.Received,
            TxPower = "100",
            WorkedOperatorName = "Taylor Operator",
            WorkedGrid = "CN87up",
            WorkedCountry = "United States",
            WorkedDxcc = 291,
            WorkedContinent = "NA",
            StationSnapshot = CreateStationSnapshot(),
            Notes = "Generated by the debug workbench.",
            Comment = "Sample QSO payload",
            CreatedAt = Timestamp.FromDateTime(utcNow),
            UpdatedAt = Timestamp.FromDateTime(utcNow),
            SyncStatus = (SyncStatus)0
        };

        if (!string.IsNullOrWhiteSpace(submode))
        {
            record.Submode = submode;
        }

        return record;
    }

    public StationProfile CreateStationProfile()
    {
        return new StationProfile
        {
            ProfileName = "Home",
            StationCallsign = "K7DBG",
            OperatorCallsign = "K7DBG",
            OperatorName = "Taylor Operator",
            Grid = "CN87up",
            County = "KING",
            State = "WA",
            Country = "United States",
            Dxcc = 291,
            CqZone = 3,
            ItuZone = 6,
            Latitude = 47.6062,
            Longitude = -122.3321
        };
    }

    public StationSnapshot CreateStationSnapshot()
    {
        return new StationSnapshot
        {
            ProfileName = "Home",
            StationCallsign = "K7DBG",
            OperatorCallsign = "K7DBG",
            OperatorName = "Taylor Operator",
            Grid = "CN87up",
            County = "KING",
            State = "WA",
            Country = "United States",
            Dxcc = 291,
            CqZone = 3,
            ItuZone = 6,
            Latitude = 47.6062,
            Longitude = -122.3321
        };
    }

    public DxccEntity CreateDxccEntity()
    {
        return new DxccEntity
        {
            DxccCode = 291,
            CountryName = "United States",
            Continent = "NA",
            ItuZone = 6,
            CqZone = 3,
            UtcOffset = -8,
            Latitude = 47.6062,
            Longitude = -122.3321,
            Notes = "Sample DXCC entity for the debug workbench."
        };
    }

    public IMessage CreateSampleMessage(System.Type messageType, string callsign, QsoSampleOptions? qsoOptions = null)
    {
        ArgumentNullException.ThrowIfNull(messageType);
        ArgumentNullException.ThrowIfNull(callsign);

        if (!typeof(IMessage).IsAssignableFrom(messageType))
        {
            throw new ArgumentException($"'{messageType.FullName}' is not a protobuf message type.", nameof(messageType));
        }

        if (CustomBuilders.TryGetValue(messageType, out var builder))
        {
            return builder(this, callsign, qsoOptions);
        }

        if (Activator.CreateInstance(messageType) is IMessage message)
        {
            return message;
        }

        throw new InvalidOperationException($"Could not create sample message for '{messageType.FullName}'.");
    }
#pragma warning restore CA1822 // Mark members as static

    private static (RstReport Sent, RstReport Received) CreateSampleRst(Mode mode)
    {
        return mode switch
        {
            Mode.Cw => (
                new RstReport { Raw = "599", Readability = 5, Strength = 9, Tone = 9 },
                new RstReport { Raw = "579", Readability = 5, Strength = 7, Tone = 9 }),
            Mode.Ft8 or Mode.Rtty or Mode.Psk or Mode.Mfsk => (
                new RstReport { Raw = "-08" },
                new RstReport { Raw = "-12" }),
            _ => (
                new RstReport { Raw = "59", Readability = 5, Strength = 9 },
                new RstReport { Raw = "57", Readability = 5, Strength = 7 })
        };
    }

    private static ulong GetSampleFrequencyKhz(Band band)
    {
        return band switch
        {
            Band._160M => 1900,
            Band._80M => 3900,
            Band._40M => 7100,
            Band._30M => 10136,
            Band._20M => 14250,
            Band._17M => 18100,
            Band._15M => 21250,
            Band._12M => 24940,
            Band._10M => 28400,
            Band._6M => 50125,
            Band._2M => 146520,
            Band._70Cm => 446000,
            _ => 14250
        };
    }

    private static string? GetSampleSubmode(Band band, Mode mode)
    {
        return mode switch
        {
            Mode.Ssb => band is Band._160M or Band._80M or Band._40M ? "LSB" : "USB",
            Mode.Ft8 => "FT8",
            _ => null
        };
    }

    private static string NormalizeCallsign(string? callsign)
    {
        return string.IsNullOrWhiteSpace(callsign)
            ? "K7DBG"
            : callsign.Trim().ToUpperInvariant();
    }
}
