#ifndef QSORIPPER_FFI_H
#define QSORIPPER_FFI_H

/* Warning: this file is autogenerated by cbindgen. Do not modify. */

/**
 * Opaque client handle holding the runtime and gRPC channels.
 */
typedef struct QsrClient QsrClient;

/**
 * RST signal report (readability, strength, optional tone).
 */
typedef struct QsrRstReport {
  /**
   * Readability (1-5).
   */
  int32_t readability;
  /**
   * Signal strength (1-9).
   */
  int32_t strength;
  /**
   * Tone (0 = not applicable, 1-9 for CW).
   */
  int32_t tone;
} QsrRstReport;

/**
 * Request to log a new QSO.
 */
typedef struct QsrLogQsoRequest {
  /**
   * Worked station callsign (null-terminated UTF-8).
   */
  uint8_t callsign[32];
  /**
   * Band string, e.g. "20M" (null-terminated).
   */
  uint8_t band[8];
  /**
   * Mode string, e.g. "SSB" (null-terminated).
   */
  uint8_t mode[8];
  /**
   * UTC date+time string "YYYY-MM-DD HH:MM" (null-terminated).
   */
  uint8_t datetime[32];
  /**
   * RST sent.
   */
  struct QsrRstReport rst_sent;
  /**
   * RST received.
   */
  struct QsrRstReport rst_rcvd;
  /**
   * Frequency in kHz (0 = not set).
   */
  uint64_t freq_khz;
  /**
   * Comment (null-terminated).
   */
  uint8_t comment[256];
  /**
   * Notes (null-terminated).
   */
  uint8_t notes[256];
  /**
   * Operator name (null-terminated).
   */
  uint8_t worked_name[64];
  /**
   * TX power (null-terminated).
   */
  uint8_t tx_power[16];
  /**
   * Submode (null-terminated).
   */
  uint8_t submode[16];
  /**
   * Contest ID (null-terminated).
   */
  uint8_t contest_id[32];
  /**
   * Serial sent (null-terminated).
   */
  uint8_t serial_sent[16];
  /**
   * Serial received (null-terminated).
   */
  uint8_t serial_rcvd[16];
  /**
   * Exchange sent (null-terminated).
   */
  uint8_t exchange_sent[64];
  /**
   * Exchange received (null-terminated).
   */
  uint8_t exchange_rcvd[64];
  /**
   * Propagation mode (null-terminated).
   */
  uint8_t prop_mode[16];
  /**
   * Satellite name (null-terminated).
   */
  uint8_t sat_name[32];
  /**
   * Satellite mode (null-terminated).
   */
  uint8_t sat_mode[16];
  /**
   * IOTA reference (null-terminated).
   */
  uint8_t iota[16];
  /**
   * ARRL section (null-terminated).
   */
  uint8_t arrl_section[16];
  /**
   * Worked state (null-terminated).
   */
  uint8_t worked_state[16];
  /**
   * Worked county (null-terminated).
   */
  uint8_t worked_county[32];
  /**
   * SKCC membership number (null-terminated).
   */
  uint8_t skcc[16];
  /**
   * Time off date+time string "YYYY-MM-DD HH:MM" (null-terminated, empty = not set).
   */
  uint8_t time_off[32];
} QsrLogQsoRequest;

/**
 * Result from logging a new QSO.
 */
typedef struct QsrLogQsoResult {
  /**
   * Assigned local UUID (null-terminated).
   */
  uint8_t local_id[64];
} QsrLogQsoResult;

/**
 * Request to update an existing QSO (same fields as log, plus local_id).
 */
typedef struct QsrUpdateQsoRequest {
  /**
   * Local UUID of the QSO to update (null-terminated).
   */
  uint8_t local_id[64];
  /**
   * Same payload as log request.
   */
  struct QsrLogQsoRequest qso;
} QsrUpdateQsoRequest;

/**
 * Full QSO detail for editing.
 */
typedef struct QsrQsoDetail {
  /**
   * Worked callsign (null-terminated).
   */
  uint8_t callsign[32];
  /**
   * Band display string (null-terminated).
   */
  uint8_t band[8];
  /**
   * Mode display string (null-terminated).
   */
  uint8_t mode[8];
  /**
   * UTC date string "YYYY-MM-DD" (null-terminated).
   */
  uint8_t date[16];
  /**
   * UTC time string "HH:MM" (null-terminated).
   */
  uint8_t time[16];
  /**
   * Frequency in MHz string (null-terminated).
   */
  uint8_t freq_mhz[16];
  /**
   * RST sent display string (null-terminated).
   */
  uint8_t rst_sent[8];
  /**
   * RST received display string (null-terminated).
   */
  uint8_t rst_rcvd[8];
  /**
   * Comment (null-terminated).
   */
  uint8_t comment[256];
  /**
   * Notes (null-terminated).
   */
  uint8_t notes[256];
  /**
   * Local UUID (null-terminated).
   */
  uint8_t local_id[64];
  /**
   * Time off string "HH:MM" (null-terminated, empty = not set).
   */
  uint8_t time_off[16];
  /**
   * Worked name (null-terminated).
   */
  uint8_t worked_name[64];
  /**
   * TX power (null-terminated).
   */
  uint8_t tx_power[16];
  /**
   * Submode (null-terminated).
   */
  uint8_t submode[16];
  /**
   * Contest ID (null-terminated).
   */
  uint8_t contest_id[32];
  /**
   * Serial sent (null-terminated).
   */
  uint8_t serial_sent[16];
  /**
   * Serial received (null-terminated).
   */
  uint8_t serial_rcvd[16];
  /**
   * Exchange sent (null-terminated).
   */
  uint8_t exchange_sent[64];
  /**
   * Exchange received (null-terminated).
   */
  uint8_t exchange_rcvd[64];
  /**
   * Propagation mode (null-terminated).
   */
  uint8_t prop_mode[16];
  /**
   * Satellite name (null-terminated).
   */
  uint8_t sat_name[32];
  /**
   * Satellite mode (null-terminated).
   */
  uint8_t sat_mode[16];
  /**
   * IOTA reference (null-terminated).
   */
  uint8_t iota[16];
  /**
   * ARRL section (null-terminated).
   */
  uint8_t arrl_section[16];
  /**
   * Worked state (null-terminated).
   */
  uint8_t worked_state[16];
  /**
   * Worked county (null-terminated).
   */
  uint8_t worked_county[32];
  /**
   * SKCC membership number (null-terminated).
   */
  uint8_t skcc[16];
} QsrQsoDetail;

/**
 * Summary of a QSO for list display.
 */
typedef struct QsrQsoSummary {
  /**
   * UTC time string (null-terminated).
   */
  uint8_t utc[24];
  /**
   * Worked callsign (null-terminated).
   */
  uint8_t callsign[16];
  /**
   * Band display string (null-terminated).
   */
  uint8_t band[8];
  /**
   * Mode display string (null-terminated).
   */
  uint8_t mode[8];
  /**
   * RST sent display string (null-terminated).
   */
  uint8_t rst_sent[8];
  /**
   * RST received display string (null-terminated).
   */
  uint8_t rst_rcvd[8];
  /**
   * Country (null-terminated).
   */
  uint8_t country[32];
  /**
   * Grid square (null-terminated).
   */
  uint8_t grid[8];
  /**
   * Local UUID (null-terminated).
   */
  uint8_t local_id[64];
} QsrQsoSummary;

/**
 * Heap-allocated list of QSO summaries.
 */
typedef struct QsrQsoList {
  /**
   * Pointer to array of summaries (owned by Rust, freed via `qsr_free_qso_list`).
   */
  struct QsrQsoSummary *items;
  /**
   * Number of items.
   */
  int32_t count;
} QsrQsoList;

/**
 * Result from a callsign lookup.
 */
typedef struct QsrLookupResult {
  /**
   * 1 = data found, 0 = not found or error.
   */
  int32_t has_data;
  /**
   * 1 = callsign not found, 0 = found or error.
   */
  int32_t not_found;
  /**
   * Error message (null-terminated, empty = no error).
   */
  uint8_t error_msg[128];
  /**
   * Formatted name (null-terminated).
   */
  uint8_t name[64];
  /**
   * QTH / city (null-terminated).
   */
  uint8_t qth[64];
  /**
   * Grid square (null-terminated).
   */
  uint8_t grid[16];
  /**
   * Country (null-terminated).
   */
  uint8_t country[64];
  /**
   * CQ zone (0 = unknown).
   */
  int32_t cq_zone;
} QsrLookupResult;

/**
 * Rig status snapshot.
 */
typedef struct QsrRigStatus {
  /**
   * 1 = connected, 0 = disconnected.
   */
  int32_t connected;
  /**
   * Frequency display string, e.g. "14.225.000" (null-terminated).
   */
  uint8_t freq_display[32];
  /**
   * Frequency in MHz string (null-terminated).
   */
  uint8_t freq_mhz[16];
  /**
   * Band string (null-terminated).
   */
  uint8_t band[8];
  /**
   * Mode string (null-terminated).
   */
  uint8_t mode[16];
} QsrRigStatus;

/**
 * Space weather data.
 */
typedef struct QsrSpaceWeather {
  /**
   * 1 = data available, 0 = no data.
   */
  int32_t has_data;
  /**
   * Planetary K-index.
   */
  double k_index;
  /**
   * Solar flux index.
   */
  double solar_flux;
  /**
   * Sunspot number.
   */
  int32_t sunspot_number;
} QsrSpaceWeather;

/**
 * Connect to the QsoRipper engine at the given endpoint.
 *
 * # Parameters
 * - `endpoint`: Null-terminated UTF-8 string, e.g. `"http://127.0.0.1:50051"`.
 *
 * # Returns
 * An opaque client handle, or null on failure (call `qsr_last_error`).
 *
 * # Safety
 * `endpoint` must be a valid null-terminated C string.
 */
struct QsrClient *qsr_connect(const char *endpoint);

/**
 * Disconnect and free the client handle.
 *
 * # Safety
 * `client` must be a pointer returned by `qsr_connect`, or null (no-op).
 */
void qsr_disconnect(struct QsrClient *client);

/**
 * Get the last error message as a null-terminated UTF-8 string.
 *
 * The returned pointer is valid until the next FFI call from the same thread.
 */
const char *qsr_last_error(void);

/**
 * Log a new QSO.
 *
 * # Returns
 * 0 on success, -1 on failure.
 *
 * # Safety
 * `client` must be a valid client pointer. `req` and `out` must be valid pointers.
 */
int32_t qsr_log_qso(struct QsrClient *client,
                    const struct QsrLogQsoRequest *req,
                    struct QsrLogQsoResult *out);

/**
 * Update an existing QSO.
 *
 * # Returns
 * 0 on success, -1 on failure.
 *
 * # Safety
 * `client` and `req` must be valid pointers.
 */
int32_t qsr_update_qso(struct QsrClient *client, const struct QsrUpdateQsoRequest *req);

/**
 * Get a single QSO by local UUID.
 *
 * # Returns
 * 0 on success, -1 on failure (not found or gRPC error).
 *
 * # Safety
 * `client` must be valid. `local_id` must be a null-terminated C string. `out` must be valid.
 */
int32_t qsr_get_qso(struct QsrClient *client, const char *local_id, struct QsrQsoDetail *out);

/**
 * Delete a QSO by local UUID.
 *
 * # Returns
 * 0 on success, -1 on failure.
 *
 * # Safety
 * `client` must be valid. `local_id` must be a null-terminated C string.
 */
int32_t qsr_delete_qso(struct QsrClient *client, const char *local_id);

/**
 * List all QSOs into a heap-allocated list.
 *
 * On success, `out->items` and `out->count` are populated. Free with `qsr_free_qso_list`.
 *
 * # Returns
 * 0 on success, -1 on failure.
 *
 * # Safety
 * `client` and `out` must be valid.
 */
int32_t qsr_list_qsos(struct QsrClient *client, struct QsrQsoList *out);

/**
 * Free a QSO list returned by `qsr_list_qsos`.
 *
 * # Safety
 * `list` must be a `QsrQsoList` populated by `qsr_list_qsos`, or have null `items`.
 */
void qsr_free_qso_list(struct QsrQsoList *list);

/**
 * Look up a callsign.
 *
 * # Returns
 * 0 on success, -1 on failure.
 *
 * # Safety
 * `client` must be valid. `callsign` must be a null-terminated C string. `out` must be valid.
 */
int32_t qsr_lookup(struct QsrClient *client, const char *callsign, struct QsrLookupResult *out);

/**
 * Get the current rig status / snapshot.
 *
 * # Returns
 * 0 on success, -1 on failure.
 *
 * # Safety
 * `client` and `out` must be valid.
 */
int32_t qsr_get_rig_status(struct QsrClient *client, struct QsrRigStatus *out);

/**
 * Get current space weather data.
 *
 * # Returns
 * 0 on success, -1 on failure.
 *
 * # Safety
 * `client` and `out` must be valid.
 */
int32_t qsr_get_space_weather(struct QsrClient *client, struct QsrSpaceWeather *out);

#endif  /* QSORIPPER_FFI_H */
