using Google.Protobuf.WellKnownTypes;
using QsoRipper.Domain;
using QsoRipper.Engine.QrzLogbook;

#pragma warning disable CA1307 // Use StringComparison for string comparison

namespace QsoRipper.Engine.QrzLogbook.Tests;

#pragma warning disable CA1707 // Remove underscores from member names

public sealed class AdifCodecTests
{
    [Fact]
    public void Parse_valid_adif_with_header()
    {
        const string adif = """
            Generated by test
            <ADIF_VER:5>3.1.7
            <EOH>
            <CALL:4>W1AW<BAND:3>20M<MODE:3>SSB<QSO_DATE:8>20240101<TIME_ON:6>123456<eor>
            """;

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Single(qsos);
        Assert.Equal("W1AW", qsos[0].WorkedCallsign);
        Assert.Equal(Band._20M, qsos[0].Band);
        Assert.Equal(Mode.Ssb, qsos[0].Mode);
        Assert.NotNull(qsos[0].UtcTimestamp);
        Assert.Equal(2024, qsos[0].UtcTimestamp.ToDateTimeOffset().Year);
        Assert.Equal(12, qsos[0].UtcTimestamp.ToDateTimeOffset().Hour);
        Assert.Equal(34, qsos[0].UtcTimestamp.ToDateTimeOffset().Minute);
        Assert.Equal(56, qsos[0].UtcTimestamp.ToDateTimeOffset().Second);
    }

    [Fact]
    public void Parse_skips_header_fields()
    {
        const string adif = "<ADIF_VER:5>3.1.7<PROGRAMID:9>QsoRipper<EOH><CALL:4>W1AW<BAND:3>20M<MODE:2>CW<QSO_DATE:8>20240601<TIME_ON:4>0800<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Single(qsos);
        Assert.Equal("W1AW", qsos[0].WorkedCallsign);
        Assert.DoesNotContain("ADIF_VER", (IDictionary<string, string>)qsos[0].ExtraFields);
        Assert.DoesNotContain("PROGRAMID", (IDictionary<string, string>)qsos[0].ExtraFields);
    }

    [Fact]
    public void Parse_without_header_treats_all_as_records()
    {
        const string adif = "<CALL:4>W1AW<BAND:3>20M<MODE:3>FT8<QSO_DATE:8>20240101<TIME_ON:4>1200<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Single(qsos);
        Assert.Equal("W1AW", qsos[0].WorkedCallsign);
        Assert.Equal(Mode.Ft8, qsos[0].Mode);
    }

    [Fact]
    public void Parse_multiple_records()
    {
        const string adif = "<EOH><CALL:4>W1AW<MODE:2>CW<QSO_DATE:8>20240101<TIME_ON:4>1200<eor><CALL:5>K7RND<MODE:3>SSB<QSO_DATE:8>20240102<TIME_ON:4>1300<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Equal(2, qsos.Count);
        Assert.Equal("W1AW", qsos[0].WorkedCallsign);
        Assert.Equal("K7RND", qsos[1].WorkedCallsign);
    }

    [Fact]
    public void Parse_maps_frequency_khz()
    {
        const string adif = "<EOH><CALL:4>W1AW<FREQ:6>14.074<MODE:3>FT8<QSO_DATE:8>20240101<TIME_ON:4>1200<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Single(qsos);
        Assert.Equal(14_074_000UL, qsos[0].FrequencyHz);
    }

    [Fact]
    public void Parse_maps_rst_reports()
    {
        const string adif = "<EOH><CALL:4>W1AW<RST_SENT:2>59<RST_RCVD:3>599<MODE:2>CW<QSO_DATE:8>20240101<TIME_ON:4>1200<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Equal("59", qsos[0].RstSent!.Raw);
        Assert.Equal(5u, qsos[0].RstSent.Readability);
        Assert.Equal(9u, qsos[0].RstSent.Strength);
        Assert.Equal("599", qsos[0].RstReceived!.Raw);
        Assert.Equal(9u, qsos[0].RstReceived.Tone);
    }

    [Fact]
    public void Parse_treats_empty_rst_fields_as_absent()
    {
        const string adif = "<EOH><CALL:4>W1AW<RST_SENT:0><RST_RCVD:0><MODE:2>CW<QSO_DATE:8>20240101<TIME_ON:4>1200<eor>";

        var qso = Assert.Single(AdifCodec.ParseAdif(adif));

        Assert.Null(qso.RstSent);
        Assert.Null(qso.RstReceived);
    }

    [Fact]
    public void Parse_maps_station_snapshot_fields()
    {
        const string adif = "<EOH><CALL:4>W1AW<STATION_CALLSIGN:5>K7RND<MY_GRIDSQUARE:4>CN87<MY_STATE:2>WA<QSO_DATE:8>20240101<TIME_ON:4>1200<MODE:3>SSB<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Equal("K7RND", qsos[0].StationCallsign);
        Assert.NotNull(qsos[0].StationSnapshot);
        Assert.Equal("K7RND", qsos[0].StationSnapshot.StationCallsign);
        Assert.Equal("CN87", qsos[0].StationSnapshot.Grid);
        Assert.Equal("WA", qsos[0].StationSnapshot.State);
    }

    [Fact]
    public void Parse_maps_qrz_logid_from_app_field()
    {
        const string adif = "<EOH><CALL:4>W1AW<APP_QRZLOG_LOGID:6>123456<MODE:2>CW<QSO_DATE:8>20240101<TIME_ON:4>1200<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Equal("123456", qsos[0].QrzLogid);
    }

    [Fact]
    public void Parse_maps_qrz_bookid()
    {
        const string adif = "<EOH><CALL:4>W1AW<APP_QRZLOG_QSO_ID:6>654321<MODE:2>CW<QSO_DATE:8>20240101<TIME_ON:4>1200<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Equal("654321", qsos[0].QrzBookid);
    }

    [Fact]
    public void Parse_unknown_fields_go_to_extra_fields()
    {
        const string adif = "<EOH><CALL:4>W1AW<MODE:2>CW<QSO_DATE:8>20240101<TIME_ON:4>1200<CUSTOM_FIELD:5>hello<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.True(qsos[0].ExtraFields.ContainsKey("CUSTOM_FIELD"));
        Assert.Equal("hello", qsos[0].ExtraFields["CUSTOM_FIELD"]);
    }

    [Fact]
    public void Parse_unrecognized_band_goes_to_extra_fields()
    {
        const string adif = "<EOH><CALL:4>W1AW<BAND:5>999cm<MODE:2>CW<QSO_DATE:8>20240101<TIME_ON:4>1200<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Equal(Band.Unspecified, qsos[0].Band);
        Assert.True(qsos[0].ExtraFields.ContainsKey("BAND"));
    }

    [Fact]
    public void Parse_tolerant_of_unterminated_tags()
    {
        // Truncated payload — parser should not throw.
        const string adif = "<EOH><CALL:4>W1AW<MODE:2>CW<QSO_DATE:8>20240101<TIME_ON:4>1200<eor><CALL:4>ABCD<BROKEN";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Single(qsos);
        Assert.Equal("W1AW", qsos[0].WorkedCallsign);
    }

    [Fact]
    public void Parse_end_timestamp()
    {
        const string adif = "<EOH><CALL:4>W1AW<MODE:2>CW<QSO_DATE:8>20240101<TIME_ON:4>1200<QSO_DATE_OFF:8>20240101<TIME_OFF:4>1215<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.NotNull(qsos[0].UtcEndTimestamp);
        Assert.Equal(12, qsos[0].UtcEndTimestamp.ToDateTimeOffset().Hour);
        Assert.Equal(15, qsos[0].UtcEndTimestamp.ToDateTimeOffset().Minute);
    }

    [Fact]
    public void Parse_contest_and_exchange_fields()
    {
        const string adif = "<EOH><CALL:4>W1AW<MODE:2>CW<QSO_DATE:8>20240101<TIME_ON:4>1200<CONTEST_ID:6>CQ-WPX<SRX:3>001<STX:3>042<SRX_STRING:2>WA<STX_STRING:2>OR<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Equal("CQ-WPX", qsos[0].ContestId);
        Assert.Equal("001", qsos[0].SerialReceived);
        Assert.Equal("042", qsos[0].SerialSent);
        Assert.Equal("WA", qsos[0].ExchangeReceived);
        Assert.Equal("OR", qsos[0].ExchangeSent);
    }

    // -- Serialization tests ------------------------------------------------

    [Fact]
    public void Serialize_single_qso_contains_core_fields()
    {
        var qso = new QsoRecord
        {
            LocalId = "test-id",
            WorkedCallsign = "W1AW",
            StationCallsign = "K7RND",
            Band = Band._20M,
            Mode = Mode.Ft8,
            UtcTimestamp = Timestamp.FromDateTimeOffset(new DateTimeOffset(2024, 6, 15, 18, 30, 0, TimeSpan.Zero)),
        };

        var adif = AdifCodec.SerializeSingleQso(qso);

        Assert.Contains("<CALL:4>W1AW", adif);
        Assert.Contains("<STATION_CALLSIGN:5>K7RND", adif);
        Assert.Contains("<BAND:3>20M", adif);
        Assert.Contains("<MODE:3>FT8", adif);
        Assert.Contains("<QSO_DATE:8>20240615", adif);
        Assert.Contains("<TIME_ON:6>183000", adif);
        Assert.Contains("<eor>", adif);
    }

    [Fact]
    public void Serialize_round_trip_preserves_core_fields()
    {
        var original = new QsoRecord
        {
            LocalId = "rt-id",
            WorkedCallsign = "K5ABC",
            StationCallsign = "K7RND",
            Band = Band._40M,
            Mode = Mode.Cw,
            UtcTimestamp = Timestamp.FromDateTimeOffset(new DateTimeOffset(2024, 3, 10, 14, 0, 0, TimeSpan.Zero)),
            FrequencyHz = 7_030_000,
            RstSent = new RstReport { Readability = 5, Strength = 9, Tone = 9, Raw = "599" },
            Notes = "Test note",
        };

        var adif = AdifCodec.SerializeSingleQso(original);
        var parsed = AdifCodec.ParseAdif($"<EOH>\n{adif}");

        Assert.Single(parsed);
        var q = parsed[0];
        Assert.Equal("K5ABC", q.WorkedCallsign);
        Assert.Equal("K7RND", q.StationCallsign);
        Assert.Equal(Band._40M, q.Band);
        Assert.Equal(Mode.Cw, q.Mode);
        Assert.Equal(7_030_000UL, q.FrequencyHz);
        Assert.Equal("599", q.RstSent!.Raw);
        Assert.Equal("Test note", q.Notes);
    }

    [Fact]
    public void Serialize_normalizes_qrz_tx_power_units()
    {
        var qso = new QsoRecord
        {
            WorkedCallsign = "W1AW",
            Band = Band._20M,
            Mode = Mode.Cw,
            UtcTimestamp = Timestamp.FromDateTimeOffset(new DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero)),
            TxPower = "100 watts",
        };

        var adif = AdifCodec.SerializeSingleQso(qso);

        Assert.Contains("<TX_PWR:3>100", adif);
    }

    [Fact]
    public void Serialize_omits_invalid_qrz_tx_power_values()
    {
        var qso = new QsoRecord
        {
            WorkedCallsign = "W1AW",
            Band = Band._20M,
            Mode = Mode.Cw,
            UtcTimestamp = Timestamp.FromDateTimeOffset(new DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero)),
            TxPower = "HIGH",
        };

        var adif = AdifCodec.SerializeSingleQso(qso);

        Assert.DoesNotContain("TX_PWR", adif);
    }

    [Fact]
    public void Serialize_extra_fields_round_trip()
    {
        var original = new QsoRecord
        {
            WorkedCallsign = "N0CALL",
            Mode = Mode.Ssb,
            Band = Band._10M,
            UtcTimestamp = Timestamp.FromDateTimeOffset(new DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero)),
        };
        original.ExtraFields["CUSTOM_APP_FIELD"] = "hello";

        var adif = AdifCodec.SerializeSingleQso(original);
        var parsed = AdifCodec.ParseAdif($"<EOH>\n{adif}");

        Assert.Single(parsed);
        Assert.Equal("hello", parsed[0].ExtraFields["CUSTOM_APP_FIELD"]);
    }

    [Fact]
    public void Serialize_emits_qrz_logid_as_app_qrzlog_logid()
    {
        // Engines must round-trip qrz_logid via APP_QRZLOG_LOGID so that
        // subsequent syncs can recognise previously-uploaded QSOs and avoid
        // re-inserting them as duplicates (root cause of the April 2026 dup bug).
        var original = new QsoRecord
        {
            WorkedCallsign = "W1AW",
            Band = Band._20M,
            Mode = Mode.Ft8,
            UtcTimestamp = Timestamp.FromDateTimeOffset(new DateTimeOffset(2024, 6, 15, 12, 0, 0, TimeSpan.Zero)),
            QrzLogid = "123456",
            QrzBookid = "bk-42",
        };

        var adif = AdifCodec.SerializeSingleQso(original);

        Assert.Contains("<APP_QRZLOG_LOGID:6>123456", adif);
        Assert.Contains("<APP_QRZLOG_QSO_ID:5>bk-42", adif);
    }

    [Fact]
    public void Serialize_then_parse_preserves_qrz_logid()
    {
        var original = new QsoRecord
        {
            WorkedCallsign = "W1AW",
            Band = Band._20M,
            Mode = Mode.Ft8,
            UtcTimestamp = Timestamp.FromDateTimeOffset(new DateTimeOffset(2024, 6, 15, 12, 0, 0, TimeSpan.Zero)),
            QrzLogid = "987654",
        };

        var adif = AdifCodec.SerializeSingleQso(original);
        var parsed = AdifCodec.ParseAdif($"<EOH>\n{adif}");

        Assert.Single(parsed);
        Assert.Equal("987654", parsed[0].QrzLogid);
        // The app key should not leak into ExtraFields — it is represented
        // by the dedicated QrzLogid domain field only.
        Assert.False(parsed[0].ExtraFields.ContainsKey("APP_QRZLOG_LOGID"));
    }

    [Fact]
    public void Qrz_adif_typed_confirmation_and_station_fields_round_trip()
    {
        const string adif = "<EOH><CALL:4>W1AW<QSO_DATE:8>20260115<TIME_ON:6>120000<BAND:3>20M<MODE:3>SSB"
            + "<ARRL_SECT:3>WWA<SKCC:6>12345T<MY_LAT:11>N047 36.372<MY_LON:11>W122 19.866"
            + "<MY_ARRL_SECT:3>WWA<MY_CQ_ZONE:1>3<MY_ITU_ZONE:1>6<QSL_SENT:1>Y<QSL_RCVD:1>R"
            + "<QSLSDATE:8>20260120<QSLRDATE:8>20260122<LOTW_QSL_SENT:1>Y<LOTW_QSL_RCVD:1>N"
            + "<EQSL_QSL_SENT:1>N<EQSL_QSL_RCVD:1>Y<eor>";

        var qso = Assert.Single(AdifCodec.ParseAdif(adif));

        Assert.Equal("WWA", qso.WorkedArrlSection);
        Assert.Equal("12345T", qso.Skcc);
        Assert.Equal(QslStatus.Yes, qso.QslSentStatus);
        Assert.Equal(QslStatus.Requested, qso.QslReceivedStatus);
        Assert.True(qso.LotwSent);
        Assert.False(qso.LotwReceived);
        Assert.False(qso.EqslSent);
        Assert.True(qso.EqslReceived);
        Assert.Equal(47.6062, qso.StationSnapshot.Latitude, precision: 4);
        Assert.Equal(-122.3311, qso.StationSnapshot.Longitude, precision: 4);
        Assert.Equal("WWA", qso.StationSnapshot.ArrlSection);
        Assert.Equal(3U, qso.StationSnapshot.CqZone);
        Assert.Equal(6U, qso.StationSnapshot.ItuZone);

        var serialized = AdifCodec.SerializeSingleQso(qso);
        Assert.Contains("<ARRL_SECT:3>WWA", serialized);
        Assert.Contains("<SKCC:6>12345T", serialized);
        Assert.Contains("<MY_LAT:11>N047 36.372", serialized);
        Assert.Contains("<MY_LON:11>W122 19.866", serialized);
        Assert.Contains("<QSL_SENT:1>Y", serialized);
        Assert.Contains("<QSL_RCVD:1>R", serialized);
        Assert.Contains("<QSLSDATE:8>20260120", serialized);
        Assert.Contains("<QSLRDATE:8>20260122", serialized);
        Assert.Contains("<LOTW_QSL_SENT:1>Y", serialized);
        Assert.Contains("<EQSL_QSL_RCVD:1>Y", serialized);
    }

    [Fact]
    public void Cw_decode_rx_wpm_round_trips_via_app_qsoripper_rx_wpm()
    {
        var original = new QsoRecord
        {
            WorkedCallsign = "W1AW",
            Band = Band._40M,
            Mode = Mode.Cw,
            UtcTimestamp = Timestamp.FromDateTimeOffset(new DateTimeOffset(2024, 6, 15, 12, 0, 0, TimeSpan.Zero)),
            CwDecodeRxWpm = 28,
        };

        var adif = AdifCodec.SerializeSingleQso(original);
        Assert.Contains("<APP_QSORIPPER_RX_WPM:2>28", adif);

        var parsed = AdifCodec.ParseAdif($"<EOH>\n{adif}");
        Assert.Single(parsed);
        Assert.True(parsed[0].HasCwDecodeRxWpm);
        Assert.Equal(28u, parsed[0].CwDecodeRxWpm);
        Assert.False(parsed[0].ExtraFields.ContainsKey("APP_QSORIPPER_RX_WPM"));
    }

    [Fact]
    public void Cw_decode_rx_wpm_invalid_value_falls_back_to_extra_fields()
    {
        const string adif = "<EOH><CALL:4>W1AW<MODE:2>CW<QSO_DATE:8>20240101<TIME_ON:4>1200<APP_QSORIPPER_RX_WPM:7>not-num<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Single(qsos);
        Assert.False(qsos[0].HasCwDecodeRxWpm);
        Assert.Equal("not-num", qsos[0].ExtraFields["APP_QSORIPPER_RX_WPM"]);
    }

    [Fact]
    public void Serialize_omits_cw_decode_rx_wpm_when_unset()
    {
        var qso = new QsoRecord
        {
            WorkedCallsign = "W1AW",
            Mode = Mode.Cw,
            Band = Band._40M,
            UtcTimestamp = Timestamp.FromDateTimeOffset(new DateTimeOffset(2024, 6, 15, 12, 0, 0, TimeSpan.Zero)),
        };

        var adif = AdifCodec.SerializeSingleQso(qso);

        Assert.DoesNotContain("APP_QSORIPPER_RX_WPM", adif);
    }

    [Fact]
    public void Cw_decode_transcript_round_trips_via_app_qsoripper_cw_transcript()
    {
        var original = new QsoRecord
        {
            WorkedCallsign = "W1AW",
            Band = Band._40M,
            Mode = Mode.Cw,
            UtcTimestamp = Timestamp.FromDateTimeOffset(new DateTimeOffset(2024, 6, 15, 12, 0, 0, TimeSpan.Zero)),
            CwDecodeTranscript = "CQ DE W1AW K",
        };

        var adif = AdifCodec.SerializeSingleQso(original);
        Assert.Contains("<APP_QSORIPPER_CW_TRANSCRIPT:12>CQ DE W1AW K", adif);

        var parsed = AdifCodec.ParseAdif($"<EOH>\n{adif}");
        Assert.Single(parsed);
        Assert.True(parsed[0].HasCwDecodeTranscript);
        Assert.Equal("CQ DE W1AW K", parsed[0].CwDecodeTranscript);
        Assert.False(parsed[0].ExtraFields.ContainsKey("APP_QSORIPPER_CW_TRANSCRIPT"));
    }

    [Fact]
    public void Serialize_omits_cw_decode_transcript_when_unset()
    {
        var qso = new QsoRecord
        {
            WorkedCallsign = "W1AW",
            Mode = Mode.Cw,
            Band = Band._40M,
            UtcTimestamp = Timestamp.FromDateTimeOffset(new DateTimeOffset(2024, 6, 15, 12, 0, 0, TimeSpan.Zero)),
        };

        var adif = AdifCodec.SerializeSingleQso(qso);

        Assert.DoesNotContain("APP_QSORIPPER_CW_TRANSCRIPT", adif);
    }

    [Fact]
    public void Cw_decode_transcript_sanitizes_non_ascii_and_control_chars()
    {
        // Include non-ASCII (é U+00E9), bell control (0x07), DEL (0x7F),
        // and a preserved newline. After sanitization the field length
        // must equal byte length so the Rust reader (byte-length writer)
        // and .NET reader (char-length writer) agree on parsing.
        var original = new QsoRecord
        {
            WorkedCallsign = "W1AW",
            Mode = Mode.Cw,
            Band = Band._40M,
            UtcTimestamp = Timestamp.FromDateTimeOffset(new DateTimeOffset(2024, 6, 15, 12, 0, 0, TimeSpan.Zero)),
            CwDecodeTranscript = "CQ\u00e9\u0007DE\u007f\nK",
        };

        var adif = AdifCodec.SerializeSingleQso(original);
        Assert.Contains("<APP_QSORIPPER_CW_TRANSCRIPT:6>CQDE\nK", adif);

        var parsed = AdifCodec.ParseAdif($"<EOH>\n{adif}");
        Assert.Equal("CQDE\nK", parsed[0].CwDecodeTranscript);
    }

    [Fact]
    public void Cw_decode_transcript_extra_fields_does_not_shadow_typed_value()
    {
        var qso = new QsoRecord
        {
            WorkedCallsign = "W1AW",
            Mode = Mode.Cw,
            Band = Band._40M,
            UtcTimestamp = Timestamp.FromDateTimeOffset(new DateTimeOffset(2024, 6, 15, 12, 0, 0, TimeSpan.Zero)),
            CwDecodeTranscript = "typed",
        };
        qso.ExtraFields["APP_QSORIPPER_CW_TRANSCRIPT"] = "stale";

        var adif = AdifCodec.SerializeSingleQso(qso);

        Assert.Contains("<APP_QSORIPPER_CW_TRANSCRIPT:5>typed", adif);
        Assert.DoesNotContain("stale", adif);
    }
}
