using Google.Protobuf.WellKnownTypes;
using QsoRipper.Domain;
using QsoRipper.Engine.QrzLogbook;

#pragma warning disable CA1307 // Use StringComparison for string comparison

namespace QsoRipper.Engine.QrzLogbook.Tests;

#pragma warning disable CA1707 // Remove underscores from member names

public sealed class AdifCodecTests
{
    [Fact]
    public void Parse_valid_adif_with_header()
    {
        const string adif = """
            Generated by test
            <ADIF_VER:5>3.1.7
            <EOH>
            <CALL:4>W1AW<BAND:3>20M<MODE:3>SSB<QSO_DATE:8>20240101<TIME_ON:6>123456<eor>
            """;

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Single(qsos);
        Assert.Equal("W1AW", qsos[0].WorkedCallsign);
        Assert.Equal(Band._20M, qsos[0].Band);
        Assert.Equal(Mode.Ssb, qsos[0].Mode);
        Assert.NotNull(qsos[0].UtcTimestamp);
        Assert.Equal(2024, qsos[0].UtcTimestamp.ToDateTimeOffset().Year);
        Assert.Equal(12, qsos[0].UtcTimestamp.ToDateTimeOffset().Hour);
        Assert.Equal(34, qsos[0].UtcTimestamp.ToDateTimeOffset().Minute);
        Assert.Equal(56, qsos[0].UtcTimestamp.ToDateTimeOffset().Second);
    }

    [Fact]
    public void Parse_skips_header_fields()
    {
        const string adif = "<ADIF_VER:5>3.1.7<PROGRAMID:9>QsoRipper<EOH><CALL:4>W1AW<BAND:3>20M<MODE:2>CW<QSO_DATE:8>20240601<TIME_ON:4>0800<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Single(qsos);
        Assert.Equal("W1AW", qsos[0].WorkedCallsign);
        Assert.DoesNotContain("ADIF_VER", (IDictionary<string, string>)qsos[0].ExtraFields);
        Assert.DoesNotContain("PROGRAMID", (IDictionary<string, string>)qsos[0].ExtraFields);
    }

    [Fact]
    public void Parse_without_header_treats_all_as_records()
    {
        const string adif = "<CALL:4>W1AW<BAND:3>20M<MODE:3>FT8<QSO_DATE:8>20240101<TIME_ON:4>1200<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Single(qsos);
        Assert.Equal("W1AW", qsos[0].WorkedCallsign);
        Assert.Equal(Mode.Ft8, qsos[0].Mode);
    }

    [Fact]
    public void Parse_multiple_records()
    {
        const string adif = "<EOH><CALL:4>W1AW<MODE:2>CW<QSO_DATE:8>20240101<TIME_ON:4>1200<eor><CALL:5>K7RND<MODE:3>SSB<QSO_DATE:8>20240102<TIME_ON:4>1300<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Equal(2, qsos.Count);
        Assert.Equal("W1AW", qsos[0].WorkedCallsign);
        Assert.Equal("K7RND", qsos[1].WorkedCallsign);
    }

    [Fact]
    public void Parse_maps_frequency_khz()
    {
        const string adif = "<EOH><CALL:4>W1AW<FREQ:6>14.074<MODE:3>FT8<QSO_DATE:8>20240101<TIME_ON:4>1200<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Single(qsos);
        Assert.Equal(14074UL, qsos[0].FrequencyKhz);
    }

    [Fact]
    public void Parse_maps_rst_reports()
    {
        const string adif = "<EOH><CALL:4>W1AW<RST_SENT:2>59<RST_RCVD:3>599<MODE:2>CW<QSO_DATE:8>20240101<TIME_ON:4>1200<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Equal("59", qsos[0].RstSent!.Raw);
        Assert.Equal(5u, qsos[0].RstSent.Readability);
        Assert.Equal(9u, qsos[0].RstSent.Strength);
        Assert.Equal("599", qsos[0].RstReceived!.Raw);
        Assert.Equal(9u, qsos[0].RstReceived.Tone);
    }

    [Fact]
    public void Parse_maps_station_snapshot_fields()
    {
        const string adif = "<EOH><CALL:4>W1AW<STATION_CALLSIGN:5>K7RND<MY_GRIDSQUARE:4>CN87<MY_STATE:2>WA<QSO_DATE:8>20240101<TIME_ON:4>1200<MODE:3>SSB<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Equal("K7RND", qsos[0].StationCallsign);
        Assert.NotNull(qsos[0].StationSnapshot);
        Assert.Equal("K7RND", qsos[0].StationSnapshot.StationCallsign);
        Assert.Equal("CN87", qsos[0].StationSnapshot.Grid);
        Assert.Equal("WA", qsos[0].StationSnapshot.State);
    }

    [Fact]
    public void Parse_maps_qrz_logid_from_app_field()
    {
        const string adif = "<EOH><CALL:4>W1AW<APP_QRZLOG_LOGID:6>123456<MODE:2>CW<QSO_DATE:8>20240101<TIME_ON:4>1200<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Equal("123456", qsos[0].QrzLogid);
    }

    [Fact]
    public void Parse_maps_qrz_bookid()
    {
        const string adif = "<EOH><CALL:4>W1AW<APP_QRZLOG_QSO_ID:6>654321<MODE:2>CW<QSO_DATE:8>20240101<TIME_ON:4>1200<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Equal("654321", qsos[0].QrzBookid);
    }

    [Fact]
    public void Parse_unknown_fields_go_to_extra_fields()
    {
        const string adif = "<EOH><CALL:4>W1AW<MODE:2>CW<QSO_DATE:8>20240101<TIME_ON:4>1200<CUSTOM_FIELD:5>hello<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.True(qsos[0].ExtraFields.ContainsKey("CUSTOM_FIELD"));
        Assert.Equal("hello", qsos[0].ExtraFields["CUSTOM_FIELD"]);
    }

    [Fact]
    public void Parse_unrecognized_band_goes_to_extra_fields()
    {
        const string adif = "<EOH><CALL:4>W1AW<BAND:5>999cm<MODE:2>CW<QSO_DATE:8>20240101<TIME_ON:4>1200<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Equal(Band.Unspecified, qsos[0].Band);
        Assert.True(qsos[0].ExtraFields.ContainsKey("BAND"));
    }

    [Fact]
    public void Parse_tolerant_of_unterminated_tags()
    {
        // Truncated payload — parser should not throw.
        const string adif = "<EOH><CALL:4>W1AW<MODE:2>CW<QSO_DATE:8>20240101<TIME_ON:4>1200<eor><CALL:4>ABCD<BROKEN";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Single(qsos);
        Assert.Equal("W1AW", qsos[0].WorkedCallsign);
    }

    [Fact]
    public void Parse_end_timestamp()
    {
        const string adif = "<EOH><CALL:4>W1AW<MODE:2>CW<QSO_DATE:8>20240101<TIME_ON:4>1200<QSO_DATE_OFF:8>20240101<TIME_OFF:4>1215<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.NotNull(qsos[0].UtcEndTimestamp);
        Assert.Equal(12, qsos[0].UtcEndTimestamp.ToDateTimeOffset().Hour);
        Assert.Equal(15, qsos[0].UtcEndTimestamp.ToDateTimeOffset().Minute);
    }

    [Fact]
    public void Parse_contest_and_exchange_fields()
    {
        const string adif = "<EOH><CALL:4>W1AW<MODE:2>CW<QSO_DATE:8>20240101<TIME_ON:4>1200<CONTEST_ID:6>CQ-WPX<SRX:3>001<STX:3>042<SRX_STRING:2>WA<STX_STRING:2>OR<eor>";

        var qsos = AdifCodec.ParseAdif(adif);

        Assert.Equal("CQ-WPX", qsos[0].ContestId);
        Assert.Equal("001", qsos[0].SerialReceived);
        Assert.Equal("042", qsos[0].SerialSent);
        Assert.Equal("WA", qsos[0].ExchangeReceived);
        Assert.Equal("OR", qsos[0].ExchangeSent);
    }

    // -- Serialization tests ------------------------------------------------

    [Fact]
    public void Serialize_single_qso_contains_core_fields()
    {
        var qso = new QsoRecord
        {
            LocalId = "test-id",
            WorkedCallsign = "W1AW",
            StationCallsign = "K7RND",
            Band = Band._20M,
            Mode = Mode.Ft8,
            UtcTimestamp = Timestamp.FromDateTimeOffset(new DateTimeOffset(2024, 6, 15, 18, 30, 0, TimeSpan.Zero)),
        };

        var adif = AdifCodec.SerializeSingleQso(qso);

        Assert.Contains("<CALL:4>W1AW", adif);
        Assert.Contains("<STATION_CALLSIGN:5>K7RND", adif);
        Assert.Contains("<BAND:3>20M", adif);
        Assert.Contains("<MODE:3>FT8", adif);
        Assert.Contains("<QSO_DATE:8>20240615", adif);
        Assert.Contains("<TIME_ON:6>183000", adif);
        Assert.Contains("<eor>", adif);
    }

    [Fact]
    public void Serialize_round_trip_preserves_core_fields()
    {
        var original = new QsoRecord
        {
            LocalId = "rt-id",
            WorkedCallsign = "K5ABC",
            StationCallsign = "K7RND",
            Band = Band._40M,
            Mode = Mode.Cw,
            UtcTimestamp = Timestamp.FromDateTimeOffset(new DateTimeOffset(2024, 3, 10, 14, 0, 0, TimeSpan.Zero)),
            FrequencyKhz = 7030,
            RstSent = new RstReport { Readability = 5, Strength = 9, Tone = 9, Raw = "599" },
            Notes = "Test note",
        };

        var adif = AdifCodec.SerializeSingleQso(original);
        var parsed = AdifCodec.ParseAdif($"<EOH>\n{adif}");

        Assert.Single(parsed);
        var q = parsed[0];
        Assert.Equal("K5ABC", q.WorkedCallsign);
        Assert.Equal("K7RND", q.StationCallsign);
        Assert.Equal(Band._40M, q.Band);
        Assert.Equal(Mode.Cw, q.Mode);
        Assert.Equal(7030UL, q.FrequencyKhz);
        Assert.Equal("599", q.RstSent!.Raw);
        Assert.Equal("Test note", q.Notes);
    }

    [Fact]
    public void Serialize_extra_fields_round_trip()
    {
        var original = new QsoRecord
        {
            WorkedCallsign = "N0CALL",
            Mode = Mode.Ssb,
            Band = Band._10M,
            UtcTimestamp = Timestamp.FromDateTimeOffset(new DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero)),
        };
        original.ExtraFields["CUSTOM_APP_FIELD"] = "hello";

        var adif = AdifCodec.SerializeSingleQso(original);
        var parsed = AdifCodec.ParseAdif($"<EOH>\n{adif}");

        Assert.Single(parsed);
        Assert.Equal("hello", parsed[0].ExtraFields["CUSTOM_APP_FIELD"]);
    }
}
